### ISSUE TITLE
Asset Precompile fails on every build

### ISSUE THREAD

**Issue by mxkris** [glitch-soc/mastodon#1302]
It seems, for some reason, the asset precompile task fails every time I upgrade glitch-soc. If I re-run the task, it ends with "Nothing to do" and then I just follow the rest of the upgrade workflow - everything seems fine afterward.

Is this safe to disregard or should I look into this more?

```mastodon@kindred:~/live$ RAILS_ENV=production bundle exec rails assets:precompile
yarn install v1.22.4
[1/6] Validating package.json...
[2/6] Resolving packages...
success Already up-to-date.
Done in 1.88s.
yarn install v1.22.4
[1/6] Validating package.json...
[2/6] Resolving packages...
[3/6] Fetching packages...
info fsevents@2.0.7: The platform "linux" is incompatible with this module.
info "fsevents@2.0.7" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/6] Linking dependencies...
warning " > react-redux-loading-bar@4.0.8" has incorrect peer dependency "react-redux@^3.0.0 || ^4.0.0 || ^5.0.0".
[5/6] Building fresh packages...
[6/6] Cleaning modules...
Done in 41.23s.
Compiling...
Compilation failed:

mastodon@kindred:~/live$ RAILS_ENV=production bundle exec rails assets:precompile
yarn install v1.22.4
[1/6] Validating package.json...
[2/6] Resolving packages...
[3/6] Fetching packages...
info fsevents@2.0.7: The platform "linux" is incompatible with this module.
info "fsevents@2.0.7" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/6] Linking dependencies...
warning " > react-redux-loading-bar@4.0.8" has incorrect peer dependency "react-redux@^3.0.0 || ^4.0.0 || ^5.0.0".
[5/6] Building fresh packages...
[6/6] Cleaning modules...
Done in 45.16s.
yarn install v1.22.4
[1/6] Validating package.json...
[2/6] Resolving packages...
[3/6] Fetching packages...
info fsevents@2.0.7: The platform "linux" is incompatible with this module.
info "fsevents@2.0.7" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/6] Linking dependencies...
warning " > react-redux-loading-bar@4.0.8" has incorrect peer dependency "react-redux@^3.0.0 || ^4.0.0 || ^5.0.0".
[5/6] Building fresh packages...
[6/6] Cleaning modules...
Done in 39.87s.
Everything's up-to-date. Nothing to do

**Comment by ThibG** [comment]
No, it's not safe to disregard. If you haven't made local changes, I suppose it may be webpack running out of memory when building the assets.

You can make sure webpack recompiles the assets by removing them first: `bundle exec rails assets:clobber`.

If the issue is not having enough memory and you can't make some more available, you could try this workaround: edit `config/webpack/production.js` and change `minimize: true` to `minimize: false` on line 34. This will make bigger javascript files, which may negatively impact clients (especially on first load, including those who would visit your public pages), but it will require much less RAM and CPU to compile.

**Comment by mxkris** [comment]
Thanks again for your time @ThibG 

So, I added the change to production.js and attempted to clobber the assets and got a walkk of ruby anger:

```mastodon@kindred:~/live/config/webpack$ bundle exec rails assets:clobber
rails aborted!
NameError: uninitialized constant Annotate
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/active_support.rb:79:in `block in load_missing_constant'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/active_support.rb:8:in `without_bootsnap_cache'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/active_support.rb:79:in `rescue in load_missing_constant'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/active_support.rb:58:in `load_missing_constant'
/home/mastodon/live/lib/tasks/auto_annotate_models.rake:45:in `<top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.1/lib/rails/engine.rb:656:in `block in run_tasks_blocks'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.1/lib/rails/engine.rb:656:in `each'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.1/lib/rails/engine.rb:656:in `run_tasks_blocks'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.1/lib/rails/application.rb:515:in `run_tasks_blocks'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.1/lib/rails/engine.rb:459:in `load_tasks'
/home/mastodon/live/Rakefile:6:in `<top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.1/lib/rails/commands/rake/rake_command.rb:22:in `block in perform'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.1/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.1/lib/rails/command.rb:48:in `invoke'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.1/lib/rails/commands.rb:18:in `<top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
bin/rails:4:in `<main>'

Caused by:
NameError: uninitialized constant Annotate
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/active_support.rb:60:in `block in load_missing_constant'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/active_support.rb:16:in `allow_bootsnap_retry'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/active_support.rb:59:in `load_missing_constant'
/home/mastodon/live/lib/tasks/auto_annotate_models.rake:45:in `<top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.1/lib/rails/engine.rb:656:in `block in run_tasks_blocks'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.1/lib/rails/engine.rb:656:in `each'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.1/lib/rails/engine.rb:656:in `run_tasks_blocks'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.1/lib/rails/application.rb:515:in `run_tasks_blocks'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.1/lib/rails/engine.rb:459:in `load_tasks'
/home/mastodon/live/Rakefile:6:in `<top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.1/lib/rails/commands/rake/rake_command.rb:22:in `block in perform'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.1/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.1/lib/rails/command.rb:48:in `invoke'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.1/lib/rails/commands.rb:18:in `<top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/home/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
bin/rails:4:in `<main>'
(See full trace by running task with --trace)

**Comment by ThibG** [comment]
this seems like you forgot to set `RAILS_ENV` to `production`

**Comment by mxkris** [comment]
Seems even with the workaround, I'm running out of swap and the compilation fails. I'll see if adding more swap space will help.

**Comment by mxkris** [comment]
Swap space added and compilation appears to not fail with or without workaround. Seems the notification bug is still around so I'll hop back to that thread. Consider this closed.

Cause: Linode sets really paltry amount of SWAP for smaller linodes, webpack WAS running out of memory and failing.

**Comment by jsailo** [comment]
So I ran into this issue after setting up my droplet in DigitalOcean. 

The configuration of the droplet being: 
 2 GB Memory / 1 AMD vCPU / 50 GB Disk - Ubuntu 20.04. 

Could it be because the CPU/RAM configurations are too low (not powerful enough) as @mxkris  has pointed out?

**Comment by ClearlyClaire** [comment]
It could be! You could try something like https://gorails.com/blog/limit-webpacker-ram-on-compile-for-production although I haven't tried myself

**Comment by jsailo** [comment]
Thanks. I set `webpack_compile_output: true` as pointed in the link and looks like it's not a memory issue. Emphasizing Point 4 here **Your webpack configuration is not creating a manifest.** 

The trace message is too long so I've truncated it.

```
yarn install v1.22.19
[1/6] Validating package.json...
[2/6] Resolving packages...
success Already up-to-date.
Done in 1.19s.
Everything's up-to-date. Nothing to do
rails aborted!
ActionView::Template::Error: Webpacker can't find locales.js in /home/mastodon/live/public/packs/manifest.json. Possible causes:
1. You want to set webpacker.yml value of compile to true for your environment
   unless you are using the `webpack -w` or the webpack-dev-server.
2. webpack has not yet re-run to reflect updates.
3. You have misconfigured Webpacker's config/webpacker.yml file.
4. Your webpack configuration is not creating a manifest.
Your manifest contains:
{
  "__offline_serviceworker": {
    "src": "/packs/__offline_serviceworker",
    "integrity": "sha256-/QAgyRlJFnFFeIX1+kXryeSquGJkmVaK0yeFx9bt/Ug="
  },
  "about.js": {
    "src": "/packs/js/about-7927f5cd3a011e6a9e6b.chunk.js",
    "integrity": "sha256-3r8FVDpeob58q/wzpKaiZch2JiJipBN6wFgnYPLtIHw="
  },
  "about.js.map": {
    "src": "/packs/js/about-7927f5cd3a011e6a9e6b.chunk.js.map",
    "integrity": "sha256-wf0wX26nMiJJ997WN22Oew5RPiYP08etUgSNzUkPlSc="
  },
  "admin.js": {
    "src": "/packs/js/admin-f1962376838b5d9c9e59.chunk.js",
    "integrity": "sha256-wqmIgYSz1IHu05Eci+eQIKECJ48GxDfJ/fgj1hyQN9c="
  },
```

**Comment by ClearlyClaire** [comment]
I think you need to do `bundle exec rails assets:clobber` first: webpack seems to think it already did the work when it ran out of memory.

**Comment by jsailo** [comment]
Thanks @ClearlyClaire. I ran the above comment in the as `su - mastodon` in the **live** folder but now I'm getting this. 

`ERROR: Missing RAILS_ENV environment variable, please set it to "production", "development", or "test".`

Upon running `gem env`, I get the following. What am I missing here? Is it a mastodon issue or a glitch-soc one?

```
RubyGems Environment:
  - RUBYGEMS VERSION: 3.2.33
  - RUBY VERSION: 3.0.4 (2022-04-12 patchlevel 208) [x86_64-linux]
  - INSTALLATION DIRECTORY: /home/mastodon/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0
  - USER INSTALLATION DIRECTORY: /home/mastodon/.local/share/gem/ruby/3.0.0
  - RUBY EXECUTABLE: /home/mastodon/.rbenv/versions/3.0.4/bin/ruby
  - GIT EXECUTABLE: /usr/bin/git
  - EXECUTABLE DIRECTORY: /home/mastodon/.rbenv/versions/3.0.4/bin
  - SPEC CACHE DIRECTORY: /home/mastodon/.local/share/gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /home/mastodon/.rbenv/versions/3.0.4/etc
  - RUBYGEMS PLATFORMS:
     - ruby
     - x86_64-linux
  - GEM PATHS:
     - /home/mastodon/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0
     - /home/mastodon/.local/share/gem/ruby/3.0.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /home/mastodon/.rbenv/versions/3.0.4/bin
     - /home/mastodon/.rbenv/libexec
     - /home/mastodon/.rbenv/plugins/ruby-build/bin
     - /home/mastodon/.rbenv/shims
     - /home/mastodon/.rbenv/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
     - /usr/games
     - /usr/local/games
     - /snap/bin
```

**Comment by ClearlyClaire** [comment]
Set `RAILS_ENV=production` as instructed, as you did before for the other commands.

**Comment by jsailo** [comment]
No luck. 

```
mastodon@masto:~/live$ RAILS_ENV=production
mastodon@masto:~/live$ bundle exec rails assets:clobber
```
1 second pause

`ERROR: Missing RAILS_ENV environment variable, please set it to "production", "development", or "test".`

**Comment by ClearlyClaire** [comment]
With bash you need to either do `RAILS_ENV=production bundle exec rails assets:clobber` or `export RAILS_ENV=production` then `bundle exec rails assets:clobber`.

**Comment by jsailo** [comment]
Failed again. 

Note that I ran `bundle exec rails assets:clobber` after doing `RAILS_ENV=production bundle exec rails assets:clobber` but this again gave the same error (snippet below).

```
mastodon@masto:~/live$ RAILS_ENV=production bundle exec rails assets:clobber
I, [2022-09-11T09:27:36.158710 #65232]  INFO -- : Removed /home/mastodon/live/public/assets
Removed webpack output path directory /home/mastodon/live/public/packs
```
Then I ran `bundle exec rails assets:clobber`
Output
```
mastodon@masto:~/live$ bundle exec rails assets:clobber
ERROR: Missing RAILS_ENV environment variable, please set it to "production", "development", or "test".
```

Nevertheless, I ran `RAILS_ENV=production bundle exec rails assets:clobber`

Output
```
mastodon@masto:~/live$ RAILS_ENV=production bundle exec rails assets:clobber
I, [2022-09-11T09:28:38.873854 #65274]  INFO -- : Removed /home/mastodon/live/public/assets
Removed webpack output path directory /home/mastodon/live/public/packs
```
Then I ran `RAILS_ENV=production bundle exec rails assets:precompile`.

Following is the output.  Compilation failed

```
mastodon@masto:~/live$ RAILS_ENV=production bundle exec rails assets:precompile
yarn install v1.22.19
[1/6] Validating package.json...
[2/6] Resolving packages...
success Already up-to-date.
Done in 1.31s.
I, [2022-09-11T09:30:09.702440 #65318]  INFO -- : Writing /home/mastodon/live/public/assets/doorkeeper/admin/application-a644908e7bab54fb749be0f59fb64a7480bbf9c4c2b79d4a65791cb7ab4d8730.css
I, [2022-09-11T09:30:09.703266 #65318]  INFO -- : Writing /home/mastodon/live/public/assets/doorkeeper/admin/application-a644908e7bab54fb749be0f59fb64a7480bbf9c4c2b79d4a65791cb7ab4d8730.css.gz
I, [2022-09-11T09:30:09.708908 #65318]  INFO -- : Writing /home/mastodon/live/public/assets/doorkeeper/application-c93dac2ad9d65e3393e0e2c958481e86ef7a5e5b0f6ce406842a7b99b25a4850.css
I, [2022-09-11T09:30:09.709308 #65318]  INFO -- : Writing /home/mastodon/live/public/assets/doorkeeper/application-c93dac2ad9d65e3393e0e2c958481e86ef7a5e5b0f6ce406842a7b99b25a4850.css.gz
I, [2022-09-11T09:30:09.718490 #65318]  INFO -- : Writing /home/mastodon/live/public/assets/pghero/favicon-db10337a56c45eb43c22ff5019546b520fa22c7281d4d385f235cbca67ed26bb.png
I, [2022-09-11T09:30:09.733985 #65318]  INFO -- : Writing /home/mastodon/live/public/assets/pghero/application-a60bf0a452ed064fef3594cf52a4c998712da7c76150f890f4eaa644f59671e4.js
I, [2022-09-11T09:30:09.735775 #65318]  INFO -- : Writing /home/mastodon/live/public/assets/pghero/application-a60bf0a452ed064fef3594cf52a4c998712da7c76150f890f4eaa644f59671e4.js.gz
I, [2022-09-11T09:30:09.748697 #65318]  INFO -- : Writing /home/mastodon/live/public/assets/pghero/application-c31338f656687c1d733bb0f48d40acd076e24060f3dcff83b34870e4ccc2789d.css
I, [2022-09-11T09:30:09.749119 #65318]  INFO -- : Writing /home/mastodon/live/public/assets/pghero/application-c31338f656687c1d733bb0f48d40acd076e24060f3dcff83b34870e4ccc2789d.css.gz
Compiling...
Compilation failed:
```

**Comment by ClearlyClaire** [comment]
Retry with something like `export NODE_OPTIONS="--max-old-space-size=350"`

**Comment by jsailo** [comment]
Apologies but my knowledge is limited. Do you mean:

`RAILS_ENV=production bundle exec rails assets:precompile export NODE_OPTIONS="--max-old-space-size=350"`

OR 

`RAILS_ENV=production bundle exec rails assets:clobber export NODE_OPTIONS="--max-old-space-size=350`

**Comment by ClearlyClaire** [comment]
I mean neither of those. In bash, do `export RAILS_ENV=production` so that subsequent commands will have the proper environment. Also do `export NODE_OPTIONS="--max-old-space-size=350"`, then run the commands you already ran. So:

```
mastodon@masto:~/live$ export RAILS_ENV=production
mastodon@masto:~/live$ export NODE_OPTIONS="--max-old-space-size=350"
mastodon@masto:~/live$ bundle exec rails assets:clobber && bundle exec rails assets:precompile
```

**Comment by jsailo** [comment]
Thanks a lot for taking the time to type that out. 

Unfortunately, it still fails. Sharing the trace message in case it give info that help.

```
mastodon@masto:~/live$ export RAILS_ENV=production
mastodon@masto:~/live$ export NODE_OPTIONS="--max-old-space-size=350"
mastodon@masto:~/live$ bundle exec rails assets:clobber && bundle exec rails assets:precompile
I, [2022-09-11T09:49:57.830875 #65653]  INFO -- : Removed /home/mastodon/live/public/assets
Removed webpack output path directory /home/mastodon/live/public/packs
yarn install v1.22.19
[1/6] Validating package.json...
[2/6] Resolving packages...
success Already up-to-date.
Done in 1.30s.
I, [2022-09-11T09:50:08.409322 #65679]  INFO -- : Writing /home/mastodon/live/public/assets/doorkeeper/admin/application-a644908e7bab54fb749be0f59fb64a7480bbf9c4c2b79d4a65791cb7ab4d8730.css
I, [2022-09-11T09:50:08.410280 #65679]  INFO -- : Writing /home/mastodon/live/public/assets/doorkeeper/admin/application-a644908e7bab54fb749be0f59fb64a7480bbf9c4c2b79d4a65791cb7ab4d8730.css.gz
I, [2022-09-11T09:50:08.412269 #65679]  INFO -- : Writing /home/mastodon/live/public/assets/doorkeeper/application-c93dac2ad9d65e3393e0e2c958481e86ef7a5e5b0f6ce406842a7b99b25a4850.css
I, [2022-09-11T09:50:08.412575 #65679]  INFO -- : Writing /home/mastodon/live/public/assets/doorkeeper/application-c93dac2ad9d65e3393e0e2c958481e86ef7a5e5b0f6ce406842a7b99b25a4850.css.gz
I, [2022-09-11T09:50:08.413570 #65679]  INFO -- : Writing /home/mastodon/live/public/assets/pghero/favicon-db10337a56c45eb43c22ff5019546b520fa22c7281d4d385f235cbca67ed26bb.png
I, [2022-09-11T09:50:08.435193 #65679]  INFO -- : Writing /home/mastodon/live/public/assets/pghero/application-a60bf0a452ed064fef3594cf52a4c998712da7c76150f890f4eaa644f59671e4.js
I, [2022-09-11T09:50:08.436735 #65679]  INFO -- : Writing /home/mastodon/live/public/assets/pghero/application-a60bf0a452ed064fef3594cf52a4c998712da7c76150f890f4eaa644f59671e4.js.gz
I, [2022-09-11T09:50:08.445292 #65679]  INFO -- : Writing /home/mastodon/live/public/assets/pghero/application-c31338f656687c1d733bb0f48d40acd076e24060f3dcff83b34870e4ccc2789d.css
I, [2022-09-11T09:50:08.446124 #65679]  INFO -- : Writing /home/mastodon/live/public/assets/pghero/application-c31338f656687c1d733bb0f48d40acd076e24060f3dcff83b34870e4ccc2789d.css.gz
Compiling...
Compilation failed:

<--- Last few GCs --->

[65735:0x53ce9d0]   106841 ms: Scavenge (reduce) 342.8 (356.1) -> 342.4 (356.3) MB, 0.9 / 0.0 ms  (average mu = 0.348, current mu = 0.371) allocation failure
[65735:0x53ce9d0]   106842 ms: Scavenge (reduce) 343.0 (356.3) -> 342.5 (356.6) MB, 1.0 / 0.0 ms  (average mu = 0.348, current mu = 0.371) allocation failure
[65735:0x53ce9d0]   107477 ms: Mark-sweep (reduce) 343.5 (356.8) -> 342.5 (357.0) MB, 633.1 / 0.0 ms  (average mu = 0.303, current mu = 0.257) allocation failure scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb02930 node::Abort() [node]
 2: 0xa18149 node::FatalError(char const*, char const*) [node]
 3: 0xcdd16e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xcdd4e7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xe94b55  [node]
 6: 0xe95636  [node]
 7: 0xea3b5e  [node]
 8: 0xea45a0 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 9: 0xea751e v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
10: 0xe68a5a v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
11: 0x11e17c6 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
12: 0x15d5439  [node]

```

**Comment by ClearlyClaire** [comment]
Alright, so the `NODE_OPTIONS="--max-old-space-size=350"` did have an effect, although it resulted in webpack running out of memory “cleanly” rather than being killed. Not sure that it's possible to limit its memory in a way that will make it behave properly, but you could try increasing the `350` and see how it fares.

Try with something like `NODE_OPTIONS="--max-old-space-size=1024"`

**Comment by jsailo** [comment]
Thanks again. It however, failed again. 
I looked around for `FATAL ERROR: Ineffective mark-compacts` and came across https://stackoverflow.com/questions/53230823/fatal-error-ineffective-mark-compacts-near-heap-limit-allocation-failed-javas
Besides the `export NODE_OPTIONS="--max-old-space-size=8192"` option, someone out there has recommended installing Node.js, version 12.10.0 but I'm already on v16.17.0.

Here's the trace message anyhows.
```
mastodon@masto:~/live$ NODE_OPTIONS="--max-old-space-size=1024"
mastodon@masto:~/live$ export RAILS_ENV=production
mastodon@masto:~/live$ export NODE_OPTIONS="--max-old-space-size=350"
mastodon@masto:~/live$ bundle exec rails assets:clobber && bundle exec rails assets:precompile
I, [2022-09-11T09:58:59.893103 #65799]  INFO -- : Removed /home/mastodon/live/public/assets
Removed webpack output path directory /home/mastodon/live/public/packs
yarn install v1.22.19
[1/6] Validating package.json...
[2/6] Resolving packages...
success Already up-to-date.
Done in 1.41s.
I, [2022-09-11T09:59:11.315730 #65826]  INFO -- : Writing /home/mastodon/live/public/assets/doorkeeper/admin/application-a644908e7bab54fb749be0f59fb64a7480bbf9c4c2b79d4a65791cb7ab4d8730.css
I, [2022-09-11T09:59:11.316557 #65826]  INFO -- : Writing /home/mastodon/live/public/assets/doorkeeper/admin/application-a644908e7bab54fb749be0f59fb64a7480bbf9c4c2b79d4a65791cb7ab4d8730.css.gz
I, [2022-09-11T09:59:11.319029 #65826]  INFO -- : Writing /home/mastodon/live/public/assets/doorkeeper/application-c93dac2ad9d65e3393e0e2c958481e86ef7a5e5b0f6ce406842a7b99b25a4850.css
I, [2022-09-11T09:59:11.320040 #65826]  INFO -- : Writing /home/mastodon/live/public/assets/doorkeeper/application-c93dac2ad9d65e3393e0e2c958481e86ef7a5e5b0f6ce406842a7b99b25a4850.css.gz
I, [2022-09-11T09:59:11.321308 #65826]  INFO -- : Writing /home/mastodon/live/public/assets/pghero/favicon-db10337a56c45eb43c22ff5019546b520fa22c7281d4d385f235cbca67ed26bb.png
I, [2022-09-11T09:59:11.345109 #65826]  INFO -- : Writing /home/mastodon/live/public/assets/pghero/application-a60bf0a452ed064fef3594cf52a4c998712da7c76150f890f4eaa644f59671e4.js
I, [2022-09-11T09:59:11.346706 #65826]  INFO -- : Writing /home/mastodon/live/public/assets/pghero/application-a60bf0a452ed064fef3594cf52a4c998712da7c76150f890f4eaa644f59671e4.js.gz
I, [2022-09-11T09:59:11.352683 #65826]  INFO -- : Writing /home/mastodon/live/public/assets/pghero/application-c31338f656687c1d733bb0f48d40acd076e24060f3dcff83b34870e4ccc2789d.css
I, [2022-09-11T09:59:11.355575 #65826]  INFO -- : Writing /home/mastodon/live/public/assets/pghero/application-c31338f656687c1d733bb0f48d40acd076e24060f3dcff83b34870e4ccc2789d.css.gz
Compiling...
Compilation failed:

<--- Last few GCs --->

[65880:0x4d829d0]   110565 ms: Scavenge (reduce) 342.6 (355.9) -> 342.1 (356.2) MB, 1.2 / 0.0 ms  (average mu = 0.360, current mu = 0.405) allocation failure
[65880:0x4d829d0]   110567 ms: Scavenge (reduce) 342.8 (356.2) -> 342.3 (356.4) MB, 1.3 / 0.0 ms  (average mu = 0.360, current mu = 0.405) allocation failure
[65880:0x4d829d0]   111182 ms: Mark-sweep (reduce) 343.0 (356.4) -> 342.3 (356.7) MB, 615.0 / 0.0 ms  (average mu = 0.303, current mu = 0.239) allocation failure scavenge might not succeed

<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb02930 node::Abort() [node]
 2: 0xa18149 node::FatalError(char const*, char const*) [node]
 3: 0xcdd16e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xcdd4e7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xe94b55  [node]
 6: 0xe95636  [node]
 7: 0xea3b5e  [node]
 8: 0xea45a0 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 9: 0xea751e v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
10: 0xe68a5a v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
11: 0x11e17c6 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
12: 0x15d5439  [node]
```

**Comment by ClearlyClaire** [comment]
Do not downgrade nodejs, the article I linked is old.

Try applying this change:
```patch
diff --git a/config/webpack/production.js b/config/webpack/production.js
index 79dcebc7c..60a18418f 100644
--- a/config/webpack/production.js
+++ b/config/webpack/production.js
@@ -13,6 +13,7 @@ const sharedConfig = require('./shared');
 const root = resolve(__dirname, '..', '..');
 
 module.exports = merge(sharedConfig, {
+  parallelism: 1,
   mode: 'production',
   devtool: 'source-map',
   stats: 'normal',
```

**Comment by jsailo** [comment]
Apologies but we are reaching the point of 'this is Greek to me'. And I don't mean to be rude. 
Thanks very much for walking me through and trying to help me resolve this issue. 

Looks like I'll have to hire an expert for this. 

Thank you again.
