### ISSUE TITLE
Api::V1::Accounts::SearchController throwing 500

### ISSUE THREAD

**Issue by rtucker** [glitch-soc/mastodon#1348]
Currently getting the following error when trying to search for accounts via the web UI:

```
web_1                                | [41c9e741-12eb-4bd3-866a-8c6abf62429d] method=GET path=/api/v1/accounts/search format=html controller=Api::V1::Accounts::SearchController action=show status=500 error='Elasticsearch::Transport::Transport::Errors::BadRequest: [400] {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"request [/accounts/account/_search] contains unrecognized parameter: [rest_total_hits_as_int]"}],"type":"illegal_argument_exception","reason":"request [/accounts/account/_search] contains unrecognized parameter: [rest_total_hits_as_int]"},"status":400}' duration=70.32 view=0.00 db=56.28
web_1                                | [41c9e741-12eb-4bd3-866a-8c6abf62429d]   
web_1                                | [41c9e741-12eb-4bd3-866a-8c6abf62429d] Elasticsearch::Transport::Transport::Errors::BadRequest ([400] {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"request [/accounts/account/_search] contains unrecognized parameter: [rest_total_hits_as_int]"}],"type":"illegal_argument_exception","reason":"request [/accounts/account/_search] contains unrecognized parameter: [rest_total_hits_as_int]"},"status":400}):
web_1                                | [41c9e741-12eb-4bd3-866a-8c6abf62429d]   
web_1                                | [41c9e741-12eb-4bd3-866a-8c6abf62429d] config/initializers/chewy.rb:37:in `search'
web_1                                | [41c9e741-12eb-4bd3-866a-8c6abf62429d] app/services/account_search_service.rb:87:in `from_elasticsearch'
web_1                                | [41c9e741-12eb-4bd3-866a-8c6abf62429d] app/services/account_search_service.rb:45:in `search_results'
web_1                                | [41c9e741-12eb-4bd3-866a-8c6abf62429d] app/services/account_search_service.rb:22:in `search_service_results'
web_1                                | [41c9e741-12eb-4bd3-866a-8c6abf62429d] app/services/account_search_service.rb:14:in `call'
web_1                                | [41c9e741-12eb-4bd3-866a-8c6abf62429d] app/controllers/api/v1/accounts/search_controller.rb:15:in `account_search'
web_1                                | [41c9e741-12eb-4bd3-866a-8c6abf62429d] app/controllers/api/v1/accounts/search_controller.rb:8:in `show'
```

Can reproduce by attempting to @ someone in a new post.

Investigation is in progress, just opening the issue so others can find it :)

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bugs also occur on vanilla Mastodon

**Comment by ThibG** [comment]
This seems like it is caused by the code that was recently added upstream (tootsuite#13828) to make ElasticSearch 7.x work. Does that means it breaks pre-7.x ES? :/

**Comment by rtucker** [comment]
It would seem so, or at least older versions of 6.x.  This looks like someone fixed it by upgrading ES: https://github.com/lo48576/mastodon/commit/1209f3e7c2911bb36061b38307540178db1e9945

**Comment by rtucker** [comment]
Upgrading to ES 6.8.9 fixes it.
