### ISSUE TITLE
After migrating from Mastodon to glitch-soc, no new posts come into my instance.

### ISSUE THREAD

**Issue by ThatOneCalculator** [glitch-soc/mastodon#1645]
### Steps to reproduce the problem

1. Follow upgrade instructions on docs
2. Restart mastodon processes
3. No new posts come in.
```
$ systemctl status mastodon-web.service mastodon-streaming.service mastodon-sidekiq.service
● mastodon-web.service - mastodon-web
     Loaded: loaded (/etc/systemd/system/mastodon-web.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2021-12-02 00:58:01 PST; 11h ago
   Main PID: 65753 (ruby2.7)
      Tasks: 31 (limit: 38401)
     Memory: 732.9M
     CGroup: /system.slice/mastodon-web.service
             ├─65753 puma 5.5.2 (tcp://127.0.0.1:3000) [live]
             ├─65927 puma: cluster worker 0: 65753 [live]
             └─65930 puma: cluster worker 1: 65753 [live]

Dec 02 12:15:58 t1c bundle[65927]: [6e1d56ca-3913-4f75-b8bf-a74de8646a59] method=GET path=/api/v1/media/107379134908155611 format=html controller=Api::V1::MediaController actio>
Dec 02 12:16:00 t1c bundle[65927]: [ef2fc9b7-8c93-447c-a02a-9abb14a9dcba] method=GET path=/api/v1/media/107379134908155611 format=html controller=Api::V1::MediaController actio>
Dec 02 12:16:02 t1c bundle[65927]: [4f0a9e7a-c3d5-4adc-b2e5-d9c918524927] method=GET path=/api/v1/media/107379134908155611 format=html controller=Api::V1::MediaController actio>
Dec 02 12:16:04 t1c bundle[65930]: [fec6c37c-b925-4670-a3ea-a5d08e5f06ec] method=GET path=/api/v1/media/107379134908155611 format=html controller=Api::V1::MediaController actio>
Dec 02 12:16:06 t1c bundle[65927]: [dd0e1e21-69f3-4a8f-a15a-b5b21de2c1ee] method=GET path=/api/v1/media/107379134908155611 format=html controller=Api::V1::MediaController actio>
Dec 02 12:16:06 t1c bundle[65927]: [f7878aa9-1e22-4464-989a-31573d463830] method=POST path=/inbox format=*/* controller=ActivityPub::InboxesController action=create status=202 >
Dec 02 12:16:08 t1c bundle[65930]: [ffb183bb-a2b4-4cea-bf1a-2e52583f1a46] method=GET path=/api/v1/media/107379134908155611 format=html controller=Api::V1::MediaController actio>
Dec 02 12:16:10 t1c bundle[65927]: [37130158-2d00-46cd-b7ae-ddebeebe3871] method=POST path=/inbox format=html controller=ActivityPub::InboxesController action=create status=202>
Dec 02 12:16:10 t1c bundle[65930]: [57d49c6b-edd1-466e-9d82-28b1bcb2b386] method=GET path=/api/v1/media/107379134908155611 format=html controller=Api::V1::MediaController actio>
Dec 02 12:16:12 t1c bundle[65927]: [018792a7-ddcd-46bc-b1ea-bc6b39ecdcf5] method=GET path=/api/v1/media/107379134908155611 format=html controller=Api::V1::MediaController actio>

● mastodon-streaming.service - mastodon-streaming
     Loaded: loaded (/etc/systemd/system/mastodon-streaming.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2021-12-02 11:01:36 PST; 1h 14min ago
   Main PID: 501260 (node)
      Tasks: 18 (limit: 38401)
     Memory: 32.4M
     CGroup: /system.slice/mastodon-streaming.service
             ├─501260 /usr/bin/node ./streaming
             └─501288 /usr/bin/node /home/mastodon/live/streaming

Dec 02 11:57:51 t1c node[501288]: verb Unsubscribe timeline:106939219958160972
Dec 02 11:57:51 t1c node[501288]: verb Unsubscribe timeline:106939219958160972:notifications
Dec 02 12:05:47 t1c node[501288]: verb Subscribe timeline:access_token:337
Dec 02 12:05:47 t1c node[501288]: verb f102ed3a-b024-46ab-83c3-7af4c0c4bc39 Starting stream from timeline:106939219958160972, timeline:106939219958160972:notifications for 1069>
Dec 02 12:05:47 t1c node[501288]: verb Subscribe timeline:106939219958160972
Dec 02 12:05:47 t1c node[501288]: verb Subscribe timeline:106939219958160972:notifications
Dec 02 12:14:09 t1c node[501288]: verb Subscribe timeline:access_token:283
Dec 02 12:14:09 t1c node[501288]: verb 4b3c9ca9-0fd4-439f-9831-49c3f59fb294 Starting stream from timeline:106683823610478858, timeline:106683823610478858:notifications for 1066>
Dec 02 12:14:09 t1c node[501288]: verb Subscribe timeline:106683823610478858
Dec 02 12:14:09 t1c node[501288]: verb Subscribe timeline:106683823610478858:notifications

● mastodon-sidekiq.service - mastodon-sidekiq
     Loaded: loaded (/etc/systemd/system/mastodon-sidekiq.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Thu 2021-12-02 00:54:27 PST; 11h ago
    Process: 60508 ExecStart=/home/mastodon/.rbenv/shims/bundle exec sidekiq -c 25 (code=exited, status=1/FAILURE)
   Main PID: 60508 (code=exited, status=1/FAILURE)
```

### Expected behaviour

New posts to come in like normal

### Actual behaviour

No new posts have come in after migrating

### Specifications

Version 3.4.3+glitch
Ruby 2.7

**Comment by ThatOneCalculator** [comment]
Sidekiq:

![Screenshot_2021-12-02-12-19-42_2560x1440](https://user-images.githubusercontent.com/44733677/144496744-05afe396-aa4f-4e84-a6dc-6be4f56ac5e6.png)

Admin dash:

![Screenshot_2021-12-02-12-20-05_2560x1440](https://user-images.githubusercontent.com/44733677/144496813-de418687-3462-40d7-a824-39c5f1681d11.png)

**Comment by ThatOneCalculator** [comment]
It might be a problem with sidekiq, but I'm honestly not sure

**Comment by ClearlyClaire** [comment]
sidekiq has indeed failed to launch for some reason. `journalctl -u mastodon-sidekiq` to read the logs

**Comment by ThatOneCalculator** [comment]
```
$ journalctl -xu  mastodon-sidekiq.service -n 100
Hint: You are currently not seeing messages from other users and the system.
      Users in groups 'adm', 'systemd-journal' can see all messages.
      Pass -q to turn off this notice.
-- Logs begin at Sun 2021-11-14 23:07:23 PST, end at Thu 2021-12-02 12:24:50 PST. --
Dec 02 00:20:17 t1c bundle[2627271]: rbenv: version `3.0.3' is not installed (set by /home/mastodon/live/.ruby-version)
Dec 02 00:20:17 t1c bundle[2627292]: rbenv: version `3.0.3' is not installed (set by /home/mastodon/live/.ruby-version)
Dec 02 00:20:17 t1c bundle[2627309]: rbenv: version `3.0.3' is not installed (set by /home/mastodon/live/.ruby-version)
Dec 02 00:20:18 t1c bundle[2627327]: rbenv: version `3.0.3' is not installed (set by /home/mastodon/live/.ruby-version)
Dec 02 00:20:18 t1c bundle[2627344]: rbenv: version `3.0.3' is not installed (set by /home/mastodon/live/.ruby-version)
-- Reboot --
Dec 02 00:21:13 t1c bundle[1241]: rbenv: version `3.0.3' is not installed (set by /home/mastodon/live/.ruby-version)
Dec 02 00:21:13 t1c bundle[1343]: rbenv: version `3.0.3' is not installed (set by /home/mastodon/live/.ruby-version)
Dec 02 00:21:14 t1c bundle[1474]: rbenv: version `3.0.3' is not installed (set by /home/mastodon/live/.ruby-version)
Dec 02 00:21:14 t1c bundle[1575]: rbenv: version `3.0.3' is not installed (set by /home/mastodon/live/.ruby-version)
Dec 02 00:21:14 t1c bundle[1686]: rbenv: version `3.0.3' is not installed (set by /home/mastodon/live/.ruby-version)
Dec 02 00:25:26 t1c bundle[10769]: rbenv: version `3.0.3' is not installed (set by /home/mastodon/live/.ruby-version)
Dec 02 00:25:26 t1c bundle[10785]: rbenv: version `3.0.3' is not installed (set by /home/mastodon/live/.ruby-version)
Dec 02 00:25:26 t1c bundle[10801]: rbenv: version `3.0.3' is not installed (set by /home/mastodon/live/.ruby-version)
Dec 02 00:25:27 t1c bundle[10817]: rbenv: version `3.0.3' is not installed (set by /home/mastodon/live/.ruby-version)
Dec 02 00:25:27 t1c bundle[10834]: rbenv: version `3.0.3' is not installed (set by /home/mastodon/live/.ruby-version)
Dec 02 00:29:07 t1c bundle[14119]: rbenv: version `3.0.3' is not installed (set by /home/mastodon/live/.ruby-version)
Dec 02 00:29:08 t1c bundle[14136]: rbenv: version `3.0.3' is not installed (set by /home/mastodon/live/.ruby-version)
Dec 02 00:29:08 t1c bundle[14153]: rbenv: version `3.0.3' is not installed (set by /home/mastodon/live/.ruby-version)
Dec 02 00:29:08 t1c bundle[14169]: rbenv: version `3.0.3' is not installed (set by /home/mastodon/live/.ruby-version)
Dec 02 00:29:08 t1c bundle[14185]: rbenv: version `3.0.3' is not installed (set by /home/mastodon/live/.ruby-version)
Dec 02 00:48:30 t1c bundle[52800]: rbenv: version `3.0.3' is not installed (set by /home/mastodon/live/.ruby-version)
Dec 02 00:48:30 t1c bundle[52826]: rbenv: version `3.0.3' is not installed (set by /home/mastodon/live/.ruby-version)
Dec 02 00:48:30 t1c bundle[52852]: rbenv: version `3.0.3' is not installed (set by /home/mastodon/live/.ruby-version)
Dec 02 00:48:31 t1c bundle[52878]: rbenv: version `3.0.3' is not installed (set by /home/mastodon/live/.ruby-version)
Dec 02 00:48:31 t1c bundle[52904]: rbenv: version `3.0.3' is not installed (set by /home/mastodon/live/.ruby-version)
Dec 02 00:54:22 t1c bundle[60228]: /usr/lib/ruby/2.7.0/rubygems.rb:275:in `find_spec_for_exe': Could not find 'bundler' (2.2.22) required by `$BUNDLER_VERSION`. (Gem::GemNotFou>
Dec 02 00:54:22 t1c bundle[60228]: To update to the latest version installed on your system, run `bundle update --bundler`.
Dec 02 00:54:22 t1c bundle[60228]: To install the missing version, run `gem install bundler:2.2.22`
Dec 02 00:54:22 t1c bundle[60228]:         from /usr/lib/ruby/2.7.0/rubygems.rb:252:in `bin_path'
Dec 02 00:54:22 t1c bundle[60228]:         from /home/mastodon/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/rubygems_integration.rb:209:in `bin_path'
Dec 02 00:54:22 t1c bundle[60228]:         from /home/mastodon/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/shared_helpers.rb:297:in `set_bundle_variables'
Dec 02 00:54:22 t1c bundle[60228]:         from /home/mastodon/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/shared_helpers.rb:76:in `set_bundle_environment'
Dec 02 00:54:22 t1c bundle[60228]:         from /home/mastodon/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/runtime.rb:22:in `setup'
Dec 02 00:54:22 t1c bundle[60228]:         from /home/mastodon/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler.rb:149:in `setup'
Dec 02 00:54:22 t1c bundle[60228]:         from /home/mastodon/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/setup.rb:20:in `block in <top (required)>'
Dec 02 00:54:22 t1c bundle[60228]:         from /home/mastodon/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/ui/shell.rb:136:in `with_level'
Dec 02 00:54:22 t1c bundle[60228]:         from /home/mastodon/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/ui/shell.rb:88:in `silence'
Dec 02 00:54:22 t1c bundle[60228]:         from /home/mastodon/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/setup.rb:20:in `<top (required)>'
Dec 02 00:54:22 t1c bundle[60228]:         from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
Dec 02 00:54:22 t1c bundle[60228]:         from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
Dec 02 00:54:23 t1c bundle[60338]: /usr/lib/ruby/2.7.0/rubygems.rb:275:in `find_spec_for_exe': Could not find 'bundler' (2.2.22) required by `$BUNDLER_VERSION`. (Gem::GemNotFou>
Dec 02 00:54:23 t1c bundle[60338]: To update to the latest version installed on your system, run `bundle update --bundler`.
Dec 02 00:54:23 t1c bundle[60338]: To install the missing version, run `gem install bundler:2.2.22`
Dec 02 00:54:23 t1c bundle[60338]:         from /usr/lib/ruby/2.7.0/rubygems.rb:252:in `bin_path'
Dec 02 00:54:23 t1c bundle[60338]:         from /home/mastodon/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/rubygems_integration.rb:209:in `bin_path'
Dec 02 00:54:23 t1c bundle[60338]:         from /home/mastodon/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/shared_helpers.rb:297:in `set_bundle_variables'
Dec 02 00:54:23 t1c bundle[60338]:         from /home/mastodon/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/shared_helpers.rb:76:in `set_bundle_environment'
Dec 02 00:54:23 t1c bundle[60338]:         from /home/mastodon/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/runtime.rb:22:in `setup'
Dec 02 00:54:23 t1c bundle[60338]:         from /home/mastodon/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler.rb:149:in `setup'
Dec 02 00:54:23 t1c bundle[60338]:         from /home/mastodon/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/setup.rb:20:in `block in <top (required)>'
Dec 02 00:54:23 t1c bundle[60338]:         from /home/mastodon/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/ui/shell.rb:136:in `with_level'
Dec 02 00:54:23 t1c bundle[60338]:         from /home/mastodon/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/ui/shell.rb:88:in `silence'
Dec 02 00:54:23 t1c bundle[60338]:         from /home/mastodon/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/setup.rb:20:in `<top (required)>'
Dec 02 00:54:23 t1c bundle[60338]:         from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
Dec 02 00:54:23 t1c bundle[60338]:         from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
Dec 02 00:54:24 t1c bundle[60403]: /usr/lib/ruby/2.7.0/rubygems.rb:275:in `find_spec_for_exe': Could not find 'bundler' (2.2.22) required by `$BUNDLER_VERSION`. (Gem::GemNotFou>
Dec 02 00:54:24 t1c bundle[60403]: To update to the latest version installed on your system, run `bundle update --bundler`.
Dec 02 00:54:24 t1c bundle[60403]: To install the missing version, run `gem install bundler:2.2.22`
Dec 02 00:54:24 t1c bundle[60403]:         from /usr/lib/ruby/2.7.0/rubygems.rb:252:in `bin_path'
Dec 02 00:54:24 t1c bundle[60403]:         from /home/mastodon/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/rubygems_integration.rb:209:in `bin_path'
Dec 02 00:54:24 t1c bundle[60403]:         from /home/mastodon/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/shared_helpers.rb:297:in `set_bundle_variables'
Dec 02 00:54:24 t1c bundle[60403]:         from /home/mastodon/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/shared_helpers.rb:76:in `set_bundle_environment'
Dec 02 00:54:24 t1c bundle[60403]:         from /home/mastodon/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/runtime.rb:22:in `setup'
Dec 02 00:54:24 t1c bundle[60403]:         from /home/mastodon/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler.rb:149:in `setup'
Dec 02 00:54:24 t1c bundle[60403]:         from /home/mastodon/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/setup.rb:20:in `block in <top (required)>'
Dec 02 00:54:24 t1c bundle[60403]:         from /home/mastodon/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/ui/shell.rb:136:in `with_level'
Dec 02 00:54:24 t1c bundle[60403]:         from /home/mastodon/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/ui/shell.rb:88:in `silence'
Dec 02 00:54:24 t1c bundle[60403]:         from /home/mastodon/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/setup.rb:20:in `<top (required)>'
Dec 02 00:54:24 t1c bundle[60403]:         from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
Dec 02 00:54:24 t1c bundle[60403]:         from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
Dec 02 00:54:25 t1c bundle[60474]: /usr/lib/ruby/2.7.0/rubygems.rb:275:in `find_spec_for_exe': Could not find 'bundler' (2.2.22) required by `$BUNDLER_VERSION`. (Gem::GemNotFou>
Dec 02 00:54:25 t1c bundle[60474]: To update to the latest version installed on your system, run `bundle update --bundler`.
Dec 02 00:54:25 t1c bundle[60474]: To install the missing version, run `gem install bundler:2.2.22`
Dec 02 00:54:25 t1c bundle[60474]:         from /usr/lib/ruby/2.7.0/rubygems.rb:252:in `bin_path'
Dec 02 00:54:25 t1c bundle[60474]:         from /home/mastodon/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/rubygems_integration.rb:209:in `bin_path'
Dec 02 00:54:25 t1c bundle[60474]:         from /home/mastodon/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/shared_helpers.rb:297:in `set_bundle_variables'
Dec 02 00:54:25 t1c bundle[60474]:         from /home/mastodon/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/shared_helpers.rb:76:in `set_bundle_environment'
Dec 02 00:54:25 t1c bundle[60474]:         from /home/mastodon/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/runtime.rb:22:in `setup'
Dec 02 00:54:25 t1c bundle[60474]:         from /home/mastodon/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler.rb:149:in `setup'
Dec 02 00:54:25 t1c bundle[60474]:         from /home/mastodon/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/setup.rb:20:in `block in <top (required)>'
Dec 02 00:54:25 t1c bundle[60474]:         from /home/mastodon/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/ui/shell.rb:136:in `with_level'
Dec 02 00:54:25 t1c bundle[60474]:         from /home/mastodon/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/ui/shell.rb:88:in `silence'
Dec 02 00:54:25 t1c bundle[60474]:         from /home/mastodon/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/setup.rb:20:in `<top (required)>'
Dec 02 00:54:25 t1c bundle[60474]:         from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
Dec 02 00:54:25 t1c bundle[60474]:         from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
Dec 02 00:54:26 t1c bundle[60508]: /usr/lib/ruby/2.7.0/rubygems.rb:275:in `find_spec_for_exe': Could not find 'bundler' (2.2.22) required by `$BUNDLER_VERSION`. (Gem::GemNotFou>
Dec 02 00:54:26 t1c bundle[60508]: To update to the latest version installed on your system, run `bundle update --bundler`.
Dec 02 00:54:26 t1c bundle[60508]: To install the missing version, run `gem install bundler:2.2.22`
Dec 02 00:54:26 t1c bundle[60508]:         from /usr/lib/ruby/2.7.0/rubygems.rb:252:in `bin_path'
Dec 02 00:54:26 t1c bundle[60508]:         from /home/mastodon/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/rubygems_integration.rb:209:in `bin_path'
Dec 02 00:54:26 t1c bundle[60508]:         from /home/mastodon/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/shared_helpers.rb:297:in `set_bundle_variables'
Dec 02 00:54:26 t1c bundle[60508]:         from /home/mastodon/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/shared_helpers.rb:76:in `set_bundle_environment'
Dec 02 00:54:26 t1c bundle[60508]:         from /home/mastodon/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/runtime.rb:22:in `setup'
Dec 02 00:54:26 t1c bundle[60508]:         from /home/mastodon/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler.rb:149:in `setup'
Dec 02 00:54:26 t1c bundle[60508]:         from /home/mastodon/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/setup.rb:20:in `block in <top (required)>'
Dec 02 00:54:26 t1c bundle[60508]:         from /home/mastodon/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/ui/shell.rb:136:in `with_level'
Dec 02 00:54:26 t1c bundle[60508]:         from /home/mastodon/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/ui/shell.rb:88:in `silence'
Dec 02 00:54:26 t1c bundle[60508]:         from /home/mastodon/.rbenv/versions/3.0.2/lib/ruby/3.0.0/bundler/setup.rb:20:in `<top (required)>'
Dec 02 00:54:26 t1c bundle[60508]:         from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
Dec 02 00:54:26 t1c bundle[60508]:         from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
```

Apparently it wants Ruby 3.0.3? I don't even see that version listed under `rbenv install --list`

**Comment by ClearlyClaire** [comment]
Yeah, Mastodon's development version has switched to 3.0.3 by default, if you're using rbenv, install that version of Ruby.

**Comment by ThatOneCalculator** [comment]
rbenv only shows up to version 3.0.2 for me lol

**Comment by ClearlyClaire** [comment]
You may need to update the list manually: https://github.com/rbenv/rbenv#updating-the-list-of-available-ruby-versions

**Comment by ThatOneCalculator** [comment]
That worked! Currently installing 3.0.3, ik it takes a while for Ruby to install. I ended up finding a little hack, I changed the text in `.rbenv/version` to `2.7.0` for now and posts are slowly filtering in. After 3.0.3 installs, I'll change it back and lyk how it goes :)

**Comment by ThatOneCalculator** [comment]
Changed back to 3.0.3, everything works fine now! Thank you for the help :heart:
