### ISSUE TITLE
Unable to deploy ElasticSearch on fresh install

### ISSUE THREAD

**Issue by Thorwegian** [glitch-soc/mastodon#1697]
### Steps to reproduce the problem

1. Deploy fresh Glitch instance.
2. Follow instructions at https://docs.joinmastodon.org/admin/optional/elasticsearch/
3. Get type casting error at indexing step:

```
user@host:~/live$ RAILS_ENV=production bin/tootctl search deploy
/home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/elasticsearch-transport-7.13.3/lib/elasticsearch/transport/transport/base.rb:218:in `__raise_transport_error': [500] {"error":{"root_cause":[{"type":"class_cast_exception","reason":"java.lang.Boolean cannot be cast to java.util.Map"}],"type":"class_cast_exception","reason":"java.lang.Boolean cannot be cast to java.util.Map"},"status":500} (Elasticsearch::Transport::Transport::Errors::InternalServerError)
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/elasticsearch-transport-7.13.3/lib/elasticsearch/transport/transport/base.rb:347:in `perform_request'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/elasticsearch-transport-7.13.3/lib/elasticsearch/transport/transport/http/faraday.rb:37:in `perform_request'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/elasticsearch-transport-7.13.3/lib/elasticsearch/transport/client.rb:192:in `perform_request'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/elasticsearch-api-7.13.3/lib/elasticsearch/api/namespace/common.rb:38:in `perform_request'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/elasticsearch-api-7.13.3/lib/elasticsearch/api/actions/indices/create.rb:48:in `create'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/chewy-7.2.4/lib/chewy/index/actions.rb:62:in `create!'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/chewy-7.2.4/lib/chewy/index/actions.rb:34:in `create'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/chewy-7.2.4/lib/chewy/index/actions.rb:116:in `purge'
	from /home/mastodon/live/lib/mastodon/search_cli.rb:58:in `block in deploy'
	from /home/mastodon/live/lib/mastodon/search_cli.rb:56:in `each'
	from /home/mastodon/live/lib/mastodon/search_cli.rb:56:in `deploy'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:116:in `invoke'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor.rb:243:in `block in subcommand'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	from bin/tootctl:8:in `<main>'
```

### Expected behaviour

Generate ElasticSearch indices

### Actual behaviour

Exception

### Specifications

commit 23a548d794b1cb5005428c6bcf73819c1944339e (HEAD -> main, origin/main, origin/HEAD)

**Comment by Thorwegian** [comment]
Basically what the Mastodon documentation tells you to do for Ubuntu. But I've already had to ignore the setup instructions once, because Glitch appears to require a higher Ruby version than what Mastodon's documentation tells you to install. Does it perhaps also require a higher Elastic version?

**Comment by ClearlyClaire** [comment]
The development version of Mastodon, which glitch-soc is based on, requires Elasticsearch 7.x

**Comment by Thorwegian** [comment]
Thanks. I'll try that. It wouldn't hurt if the Glitch documentation mentioned it, and the requirement for Ruby 3.0.3. I'm a developer by profession but I know little about the Mastodon developer ecosystem.

**Comment by ClearlyClaire** [comment]
It doesn't require Ruby 3.0.3. It should be compatible with anything starting with Ruby 2.5, just like upstream.

**Comment by Thorwegian** [comment]
I got an error message telling me to use Ruby 3.0.3. It began working once I installed that.

**Comment by ClearlyClaire** [comment]
Ruby 3.0.3 is just the default when using `rbenv`, but anything from Ruby 2.5 is supported.

**Comment by Thorwegian** [comment]
Come to think of it, it may have been meant as a warning, but I may have understood it as an error. I didn't want to have any difficulties, so I changed that step.

The documentation needs a little love. Couldn't we fork Mastodon's and make it better?

**Comment by Thorwegian** [comment]
Using a newer ElasticSearch version worked. I guess the ticket can be closed.
