### ISSUE TITLE
Error pre-compiling static assets

### ISSUE THREAD

**Issue by retiolus** [glitch-soc/mastodon#1745]
### Steps to reproduce the problem

1. Server running Mastodon v3.5.0+glitch
2. Follow steps as specified in https://glitch-soc.github.io/docs/
3. After running `RAILS_ENV=production bundle exec rails assets:precompile` i get this error:

```
RAILS_ENV=production bundle exec rails assets:precompile
yarn install v1.22.18
[1/6] Validating package.json...
[2/6] Resolving packages...
[3/6] Fetching packages...
[4/6] Linking dependencies...
warning " > react-redux-loading-bar@4.0.8" has incorrect peer dependency "react-redux@^3.0.0 || ^4.0.0 || ^5.0.0".
warning Workspaces can only be enabled in private projects.
[5/6] Building fresh packages...
[6/6] Cleaning modules...
Done in 8.04s.
Compiling...



Compilation failed:
internal/child_process.js:408
    throw errnoException(err, 'spawn');
    ^

Error: spawn ENOMEM
    at ChildProcess.spawn (internal/child_process.js:408:11)
    at spawn (child_process.js:553:9)
    at fork (child_process.js:121:10)
    at ChildProcessWorker.initialize (/home/mastodon/live/node_modules/terser-webpack-plugin/node_modules/jest-worker/build/workers/ChildProcessWorker.js:141:45)
    at ChildProcessWorker._onExit (/home/mastodon/live/node_modules/terser-webpack-plugin/node_modules/jest-worker/build/workers/ChildProcessWorker.js:274:12)
    at ChildProcess.emit (events.js:314:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12) {
  errno: 'ENOMEM',
  code: 'ENOMEM',
  syscall: 'spawn'
}
```

### Expected behaviour

Pre-compile static assets

### Actual behaviour

Error

### Specifications

v3.5.1

**Comment by ClearlyClaire** [comment]
You're running out of memory.

**Comment by retiolus** [comment]
Hi, thanks for your answer, I guess the only solution is to add more memory?

**Comment by retiolus** [comment]
Also, I don't know if it's related to this update error, but the new /web/explore page doesn't exist, even after the update.

**Comment by ClearlyClaire** [comment]
You basically have three solutions:
- have more available RAM to complete the `assets:precompile` step
- build the assets on another machine with more RAM (they are built in `public/packs`)
- change `config/webpack/production.js` to disable minimization and the analyzer plugin, as I believe those are the most RAM-hungry parts of the `assets:precompile` step, but disabling the minimization will result in larger files being served to your users

> Also, I don't know if it's related to this update error, but the new /web/explore page doesn't exist, even after the update.

This feature has not been ported to the glitch-soc flavor yet.

**Comment by tribela** [comment]
There are ENV var option to reduce ram usage on webpack
https://blog.m4x.io/2021/webpack-how-to-fix-out-of-memory/
