### ISSUE TITLE
Due to a bug in our code or a browser compatibility issue, this page could not be displayed correctly.

### ISSUE THREAD

**Issue by cdedert** [glitch-soc/mastodon#1894]
### Steps to reproduce the problem

1. Log in on any device with the ADMIN credentials
2.Tap the notifications
3. Says Due to a bug in our code or a browser compatibility issue, this page could not be displayed correctly. and asks to reload the page.
4. Reloads the page but still can't use notifications
5. tested a different browser and same
6. tested a different account, it works fine
7. Rebooted server and same behavior
...

### Expected behaviour

Show my notifications

### Actual behaviour

Page comes up says: Due to a bug in our code or a browser compatibility issue, this page could not be displayed correctly.  Try refreshing the page. If that does not help, you may still be able to use Mastodon through a different browser or native app.

### Detailed description

When I tap the notifications icon, it opens a page saying:
 _Due to a bug in our code or a browser compatibility issue, this page could not be displayed correctly.

Try refreshing the page. If that does not help, you may still be able to use Mastodon through a different browser or native app._

Tried to reboot the server and several different browsers, same behavior. Tried different settings and flavours, still same behavior. Doesn't do this on another accounts, just admin.

### Specifications

v3.5.3+glitch

Vivaldi and firefox
Linux Mint

**Comment by ClearlyClaire** [comment]
Can you paste the error trace? I think it's an already-fixed issue with report notifications, but I am not sure.

**Comment by cdedert** [comment]
Is this what you are looking for?

Stack trace
-----------

```
TypeError: Cannot read properties of null (reading 'get')
TypeError: Cannot read properties of null (reading 'get')
    at K.render (https://theres.life/packs/js/flavours/glitch/async/notifications-9a6aa3343777a6fdf3a4.chunk.js:1:9247)
    at Bi (https://theres.life/packs/js/flavours/glitch/home-4591a668beb83754ea07.chunk.js:2:329847)
    at qi (https://theres.life/packs/js/flavours/glitch/home-4591a668beb83754ea07.chunk.js:2:329642)
    at Os (https://theres.life/packs/js/flavours/glitch/home-4591a668beb83754ea07.chunk.js:2:365256)
    at bl (https://theres.life/packs/js/flavours/glitch/home-4591a668beb83754ea07.chunk.js:2:356697)
    at ml (https://theres.life/packs/js/flavours/glitch/home-4591a668beb83754ea07.chunk.js:2:356622)
    at sl (https://theres.life/packs/js/flavours/glitch/home-4591a668beb83754ea07.chunk.js:2:353652)
    at https://theres.life/packs/js/flavours/glitch/home-4591a668beb83754ea07.chunk.js:2:305293
    at t.unstable_runWithPriority (https://theres.life/packs/js/flavours/glitch/home-4591a668beb83754ea07.chunk.js:2:380349)
    at Go (https://theres.life/packs/js/flavours/glitch/home-4591a668beb83754ea07.chunk.js:2:305002)
```Mapped stack trace
-----------

```
TypeError: Cannot read properties of null (reading 'get')
render (webpack:///app/javascript/home/mastodon/live/app/javascript/flavours/glitch/features/notifications/components/admin_report.js:84:33)
gi (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:4235:75)
Lg (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:4226:9)
fi (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:6542:85)
Qj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:6006:10)
Kj (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5998:26)
Ej (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:5741:6)
cg (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:2776:17)
unstable_runWithPriority (webpack:///node_modules/scheduler/cjs/scheduler.production.min.js:309:11)
cg (webpack:///node_modules/react-dom/cjs/react-dom.production.min.js:2742:9)
```


React component stack
---------------------

```

    in K
    in Connect(K)
    in V
    in Connect(V)
    in article
    in m
    in Connect(m)
    in div
    in div
    in n
    in w
    in Connect(w)
    in Connect(w)
    in div
    in s
    in xt
    in InjectIntl(xt)
    in Connect(InjectIntl(xt))
    in l
    in Connect(l)
    in t
    in V
    in t
    in K
    in div
    in div
    in div
    in div
    in ReactSwipableView
    in div
    in div
    in Ae
    in InjectIntl(Ae)
    in Connect(InjectIntl(Ae))
    in Connect(InjectIntl(Ae))
    in ut
    in div
    in div
    in t
    in t
    in st
    in t
    in withRouter(st)
    in InjectIntl(withRouter(st))
    in Connect(InjectIntl(withRouter(st)))
    in t
    in t
    in t
    in withRouter(t)
    in t
    in t
    in yt
    in f
    in IntlProvider
    in Et
```

**Comment by ClearlyClaire** [comment]
Yup!

Then yes, it's been fixed, you just need to update!

**Comment by cdedert** [comment]
Ok, I'm updating the server soon.
