### ISSUE TITLE
can't access admin dashboard or authorized apps after upgrade

### ISSUE THREAD

**Issue by selfagency** [glitch-soc/mastodon#2093]
### Steps to reproduce the problem

1. upgrade to latest version following directions on docs page
2. visit preferences > admin
3. see 500 page

1. upgrade to latest version following directions on docs page
2. visit preferences > account > authorized apps
3. see 500 page

### Expected behaviour

to not get a 500 error

### Actual behaviour

got a 500 error

### Detailed description

for some reason since upgrading, i can no longer access the admin dashboard or my authorized apps. i don't know if it's just me or even how to really debug this since i can't find where the logs are.

### Specifications

v4.1.0rc1+glitch
ruby 3.0.4p208
node v16.19.0

**Comment by ClearlyClaire** [comment]
I wonder if this is https://github.com/mastodon/mastodon/pull/23144#issuecomment-1398457397
Does your domain use a two-letters top-level domain?

**Comment by selfagency** [comment]
@ClearlyClaire it does not but i did manage to find an error

```
Jan 21 22:10:20 selfagency-homelab bundle[1186901]: [4a4fdbb2-ebfb-4e07-a81b-ef740ced03dc] HTTPClient::KeepAliveDisconnected (HTTPClient::KeepAliveDisconnected: ):
Jan 21 22:10:20 selfagency-homelab bundle[1186901]: [4a4fdbb2-ebfb-4e07-a81b-ef740ced03dc]
Jan 21 22:10:20 selfagency-homelab bundle[1186901]: [4a4fdbb2-ebfb-4e07-a81b-ef740ced03dc] app/lib/admin/system_check/elasticsearch_check.rb:33:in `running_version'
Jan 21 22:10:20 selfagency-homelab bundle[1186901]: [4a4fdbb2-ebfb-4e07-a81b-ef740ced03dc] app/lib/admin/system_check/elasticsearch_check.rb:11:in `pass?'
Jan 21 22:10:20 selfagency-homelab bundle[1186901]: [4a4fdbb2-ebfb-4e07-a81b-ef740ced03dc] app/lib/admin/system_check.rb:15:in `block in perform'
Jan 21 22:10:20 selfagency-homelab bundle[1186901]: [4a4fdbb2-ebfb-4e07-a81b-ef740ced03dc] app/lib/admin/system_check.rb:12:in `each'
Jan 21 22:10:20 selfagency-homelab bundle[1186901]: [4a4fdbb2-ebfb-4e07-a81b-ef740ced03dc] app/lib/admin/system_check.rb:12:in `each_with_object'
Jan 21 22:10:20 selfagency-homelab bundle[1186901]: [4a4fdbb2-ebfb-4e07-a81b-ef740ced03dc] app/lib/admin/system_check.rb:12:in `perform'
Jan 21 22:10:20 selfagency-homelab bundle[1186901]: [4a4fdbb2-ebfb-4e07-a81b-ef740ced03dc] app/controllers/admin/dashboard_controller.rb:10:in `index'
Jan 21 22:10:20 selfagency-homelab bundle[1186901]: [4a4fdbb2-ebfb-4e07-a81b-ef740ced03dc] app/controllers/concerns/localized.rb:11:in `set_locale'
Jan 21 22:10:20 selfagency-homelab bundle[1186901]: [4a4fdbb2-ebfb-4e07-a81b-ef740ced03dc] lib/mastodon/rack_middleware.rb:9:in `call'
Jan 21 22:10:23 selfagency-homelab bundle[1186906]: [3650328e-9e2f-4116-a931-c1127c56926f] method=POST path=/inbox format=html controller=Act
```

**Comment by selfagency** [comment]
and the other

```
Jan 21 22:13:12 selfagency-homelab bundle[1186906]: [6cc782ed-decd-4e35-8d95-d65d38c67aed] ActionView::Template::Error (Failed to match sequence ((NAMESPACE COLON)? (ACCESS COLON TERM / ACCESS / TERM)) at line 1 >
Jan 21 22:13:12 selfagency-homelab bundle[1186906]: [6cc782ed-decd-4e35-8d95-d65d38c67aed]     33:
Jan 21 22:13:12 selfagency-homelab bundle[1186906]: [6cc782ed-decd-4e35-8d95-d65d38c67aed]     34:       .announcements-list__item__permissions
Jan 21 22:13:12 selfagency-homelab bundle[1186906]: [6cc782ed-decd-4e35-8d95-d65d38c67aed]     35:         %ul.permissions-list
Jan 21 22:13:12 selfagency-homelab bundle[1186906]: [6cc782ed-decd-4e35-8d95-d65d38c67aed]     36:           - grouped_scopes(application.scopes).each do |scope|
Jan 21 22:13:12 selfagency-homelab bundle[1186906]: [6cc782ed-decd-4e35-8d95-d65d38c67aed]     37:             %li.permissions-list__item
Jan 21 22:13:12 selfagency-homelab bundle[1186906]: [6cc782ed-decd-4e35-8d95-d65d38c67aed]     38:               .permissions-list__item__icon
Jan 21 22:13:12 selfagency-homelab bundle[1186906]: [6cc782ed-decd-4e35-8d95-d65d38c67aed]     39:                 = fa_icon('check')
Jan 21 22:13:12 selfagency-homelab bundle[1186906]: [6cc782ed-decd-4e35-8d95-d65d38c67aed]
Jan 21 22:13:12 selfagency-homelab bundle[1186906]: [6cc782ed-decd-4e35-8d95-d65d38c67aed] app/helpers/application_helper.rb:235:in `block in grouped_scopes'
Jan 21 22:13:12 selfagency-homelab bundle[1186906]: [6cc782ed-decd-4e35-8d95-d65d38c67aed] app/helpers/application_helper.rb:234:in `each_with_object'
Jan 21 22:13:12 selfagency-homelab bundle[1186906]: [6cc782ed-decd-4e35-8d95-d65d38c67aed] app/helpers/application_helper.rb:234:in `grouped_scopes'
Jan 21 22:13:12 selfagency-homelab bundle[1186906]: [6cc782ed-decd-4e35-8d95-d65d38c67aed] app/views/oauth/authorized_applications/index.html.haml:36
Jan 21 22:13:12 selfagency-homelab bundle[1186906]: [6cc782ed-decd-4e35-8d95-d65d38c67aed] app/views/oauth/authorized_applications/index.html.haml:9
Jan 21 22:13:12 selfagency-homelab bundle[1186906]: [6cc782ed-decd-4e35-8d95-d65d38c67aed] app/controllers/concerns/localized.rb:11:in `set_locale'
Jan 21 22:13:12 selfagency-homelab bundle[1186906]: [6cc782ed-decd-4e35-8d95-d65d38c67aed] lib/mastodon/rack_middleware.rb:9:in `call'
```

**Comment by ClearlyClaire** [comment]
ok, the first one sounds like an ElasticSearch failure, the second is you having a buggy app record, not sure how to best deal with that though

**Comment by selfagency** [comment]
huh interesting, thanks, will poke around a bit

**Comment by selfagency** [comment]
i deleted auth for everything but the web app and now the first problem is resolved. i also turned off elasticsearch in the .env file and now i can access the admin page.

**Comment by selfagency** [comment]
other issue was a security setting in es

thanks for your help
