### ISSUE TITLE
ActiveModel::UnknownAttributeError (unknown attribute 'content_type' for Status.): when trying to load any pages 

### ISSUE THREAD

**Issue by itZzenXX** [glitch-soc/mastodon#2130]
### Steps to reproduce the problem

1. Setup Mastodon by following the official docs 
2. Migrate to Glitch-Soc by following the official docs
3. Go to any page while being logged in
4. ActiveModel::UnknownAttributeError (unknown attribute 'content_type' for Status.): will be spit out in the logs for the mastodon-web service.

### Expected behaviour

Migration should have been successful 

### Actual behaviour

500 Internal Server Errors when attempting to view any pages

### Detailed description

Expanded log for this issue:
```
Mar 09 19:37:17 plus.st bundle[298641]: [47847ea3-3594-450d-8c40-7be6c9a5ac9e]
Mar 09 19:37:17 plus.st bundle[298641]: [47847ea3-3594-450d-8c40-7be6c9a5ac9e] app/controllers/concerns/cache_concern.rb:34:in `cache_collection'
Mar 09 19:37:17 plus.st bundle[298641]: [47847ea3-3594-450d-8c40-7be6c9a5ac9e] app/controllers/activitypub/collections_controller.rb:23:in `block in set_items'
Mar 09 19:37:17 plus.st bundle[298641]: [47847ea3-3594-450d-8c40-7be6c9a5ac9e] app/controllers/activitypub/collections_controller.rb:71:in `for_signed_account'
Mar 09 19:37:17 plus.st bundle[298641]: [47847ea3-3594-450d-8c40-7be6c9a5ac9e] app/controllers/activitypub/collections_controller.rb:23:in `set_items'
Mar 09 19:37:17 plus.st bundle[298641]: [47847ea3-3594-450d-8c40-7be6c9a5ac9e] lib/mastodon/rack_middleware.rb:9:in `call'
Mar 09 19:37:17 plus.st bundle[298641]: [83573e5a-65b5-4644-88dc-1aea7a09c113] method=GET path=/.well-known/host-meta format=xml controller=WellKnown::HostMetaController action=show status=200 duration=0.65 view=0.33 db=0.00
Mar 09 19:37:17 plus.st bundle[298641]: [a0c76d88-ecb3-43bb-a8f8-7874c9ae40f3] method=GET path=/.well-known/webfinger format=xml controller=WellKnown::WebfingerController action=show status=200 duration=2.73 view=1.00 db=0.24
Mar 09 19:37:17 plus.st bundle[298641]: [b0b83b8b-b848-4b7d-96cd-96678fa83dc6] method=GET path=/users/itzzenxx format=json controller=AccountsController action=show status=200 duration=7.29 view=0.22 db=0.34 key=https://vibewave.space/internal/fetch#main-key
Mar 09 19:37:17 plus.st bundle[298641]: [23ab5751-a917-4b42-97d2-235b472a12f4] method=GET path=/users/itzzenxx/collections/featured format=json controller=ActivityPub::CollectionsController action=show status=500 error='ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR:  column statuses.local_only does not exist
Mar 09 19:37:17 plus.st bundle[298641]: LINE 1: ... IS NULL AND "status_pins"."account_id" = $1 AND ("statuses"...
Mar 09 19:37:17 plus.st bundle[298641]:                                                              ^
Mar 09 19:37:17 plus.st bundle[298641]: ' duration=6.68 view=0.00 db=0.67 key=https://vibewave.space/internal/fetch#main-key
Mar 09 19:37:17 plus.st bundle[298641]: [23ab5751-a917-4b42-97d2-235b472a12f4]
Mar 09 19:37:17 plus.st bundle[298641]: [23ab5751-a917-4b42-97d2-235b472a12f4] ActiveRecord::StatementInvalid (PG::UndefinedColumn: ERROR:  column statuses.local_only does not exist
Mar 09 19:37:17 plus.st bundle[298641]: LINE 1: ... IS NULL AND "status_pins"."account_id" = $1 AND ("statuses"...
Mar 09 19:37:17 plus.st bundle[298641]:                                                              ^
Mar 09 19:37:17 plus.st bundle[298641]: ):
```

### Specifications

Mastodon 4.1.0
Ruby 3.2.1
Node.js 19.7.0

**Comment by ClearlyClaire** [comment]
It seems you may not have run `bundle exec rails db:migrate`, it errorred out, or you forgot to restart the services afterwards.

**Comment by ClearlyClaire** [comment]
Are you using docker or something like that? Is your installation perhaps split into multiple servers? If so, are you sure the glitch-soc code is checked out where you ran `bundle exec rails db:migrate`? The columns that are reported as not existing should definitely be added by glitch-soc migrations.

**Comment by ClearlyClaire** [comment]
What happens if you do `RAILS_LOG_LEVEL=debug bundle exec rails db:migrate:up VERSION=20171210213213`?

**Comment by itZzenXX** [comment]
Here is the output:
```
[mastodon@plus live]$ RAILS_LOG_LEVEL=debug bundle exec rails db:migrate:up VERSION=20171210213213
   (0.6ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
   (0.1ms)  SELECT pg_try_advisory_lock(78736240045650285)
   (0.4ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
  ActiveRecord::InternalMetadata Load (0.2ms)  SELECT "ar_internal_metadata".* FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = $1 LIMIT $2  [["key", "environment"], ["LIMIT", 1]]
   (0.2ms)  SELECT pg_advisory_unlock(78736240045650285)
```

**Comment by ClearlyClaire** [comment]
It seems like it behaves as if the migrations had been run, without actually running it… not sure in which situation it would do that. Have you previously tried running glitch-soc or another fork?

**Comment by itZzenXX** [comment]
I have tried to migrate to glitch-soc before, but with the same issues, so I migrated back to upstream mastodon before I decided to try again a few days later.

**Comment by ClearlyClaire** [comment]
Alright. What happens if you do `bundle exec rails db:migrate:down VERSION=20171210213213`?

**Comment by ClearlyClaire** [comment]
oh, this is really annoying… wait a moment, I'm trying to come up with something to make Rails run the glitch-soc migrations it is pretending to have run…

**Comment by ClearlyClaire** [comment]
Can you run `ActiveRecord::SchemaMigration.where(version: ['20171210213213', '20190512200918', '20220209175231']).delete_all` in a Rails console (`bundle exec rails c`) and try `bundle exec rails db:migrate` again?

**Comment by itZzenXX** [comment]
Here is the output:
```
[mastodon@plus live]$ bundle exec rails c
Chewy console strategy is `urgent`
Loading production environment (Rails 6.1.7.2)
irb(main):001:0> ActiveRecord::SchemaMigration.where(version: ['20171210213213', '201905122009
18', '20220209175231']).delete_all
=> 3
irb(main):002:0>
[mastodon@plus live]$ bundle exec rails db:migrate
Migrating to AddLocalOnlyFlagToStatuses (20171210213213)
== 20171210213213 AddLocalOnlyFlagToStatuses: migrating =======================
[strong_migrations] DANGER: No lock timeout set
-- add_column(:statuses, :local_only, :boolean)
   -> 0.0011s
== 20171210213213 AddLocalOnlyFlagToStatuses: migrated (0.0016s) ==============

Migrating to AddContentTypeToStatuses (20190512200918)
== 20190512200918 AddContentTypeToStatuses: migrating =========================
[strong_migrations] DANGER: No lock timeout set
-- add_column(:statuses, :content_type, :string)
   -> 0.0006s
== 20190512200918 AddContentTypeToStatuses: migrated (0.0010s) ================

Migrating to AddContentTypeToStatusEdits (20220209175231)
== 20220209175231 AddContentTypeToStatusEdits: migrating ======================
[strong_migrations] DANGER: No lock timeout set
-- add_column(:status_edits, :content_type, :string)
   -> 0.0007s
== 20220209175231 AddContentTypeToStatusEdits: migrated (0.0009s) =============

[mastodon@plus live]$
```

**Comment by ClearlyClaire** [comment]
That seems much better! Does restarting the services work, now?

**Comment by itZzenXX** [comment]
Yes! Things seem to be working well now. Thank you so much!

**Comment by ClearlyClaire** [comment]
You're welcome. I wonder why Rails considered those migrations as done, though, I'll need to investigate that.
