### ISSUE TITLE
NoMethodError (undefined method `translatable?' for #<Status

### ISSUE THREAD

**Issue by nanos** [glitch-soc/mastodon#2137]
### Steps to reproduce the problem

I merged the latest changes from upstream. See https://github.com/nanos/mastodon/commit/2233f394e6b9c38a9c47f64e0efb9b32a5b496c9

Then tried to load the home timeline

### Expected behaviour

home timeline loads

### Actual behaviour

Getting the error below

### Detailed description

Here is the error message in full:

```
Mar 17 17:25:00 mstdn bundle[1551720]: [eb5b57cb-93ef-4b70-87e3-593438fe0044] method=GET path=/api/v1/accounts/##########/statuses format=html controller=Api::V1::Accounts::StatusesController action=index status=500 error='NoMethodError: undefined method `translatable?' for #<Status id: 110025822611930070, uri: "https://xxxxxx.bar/users/xxxxx/statuses/110025822...", text: "<p>ok we&#39;re back</p>", created_at: "2023-03-15 06:13:38.000000000 +0000", updated_at: "2023-03-17 12:59:57.741850000 +0000", in_reply_to_id: nil, reblog_of_id: nil, url: "https://xxxxxx.bar/@xxxxx/##########", sensitive: false, visibility: "public", spoiler_text: "", reply: false, language: "en", conversation_id: 1998198, local: false, account_id: ##########, application_id: nil, in_reply_to_account_id: nil, poll_id: nil, deleted_at: nil, edited_at: nil, trendable: nil, ordered_media_attachment_ids: nil, local_only: nil, content_type: nil>' duration=95.21 view=0.00 db=56.85
Mar 17 17:25:00 mstdn bundle[1551720]: [eb5b57cb-93ef-4b70-87e3-593438fe0044]
Mar 17 17:25:00 mstdn bundle[1551720]: [eb5b57cb-93ef-4b70-87e3-593438fe0044] NoMethodError (undefined method `translatable?' for #<Status id: 110025822611930070, uri: "https://xxxxxx.bar/users/xxxxx/statuses/110025822...", text: "<p>ok we&#39;re back</p>", created_at: "2023-03-15 06:13:38.000000000 +0000", updated_at: "2023-03-17 12:59:57.741850000 +0000", in_reply_to_id: nil, reblog_of_id: nil, url: "https://xxxxxx.bar/@xxxxx/##########", sensitive: false, visibility: "public", spoiler_text: "", reply: false, language: "en", conversation_id: 1998198, local: false, account_id: ##########, application_id: nil, in_reply_to_account_id: nil, poll_id: nil, deleted_at: nil, edited_at: nil, trendable: nil, ordered_media_attachment_ids: nil, local_only: nil, content_type: nil>):
Mar 17 17:25:00 mstdn bundle[1551720]: [eb5b57cb-93ef-4b70-87e3-593438fe0044]
Mar 17 17:25:00 mstdn bundle[1551720]: [eb5b57cb-93ef-4b70-87e3-593438fe0044] app/serializers/rest/status_serializer.rb:56:in `translatable'
Mar 17 17:25:00 mstdn bundle[1551720]: [eb5b57cb-93ef-4b70-87e3-593438fe0044] app/controllers/api/v1/accounts/statuses_controller.rb:11:in `index'
Mar 17 17:25:00 mstdn bundle[1551720]: [eb5b57cb-93ef-4b70-87e3-593438fe0044] app/controllers/concerns/localized.rb:11:in `set_locale'
Mar 17 17:25:00 mstdn bundle[1551720]: [eb5b57cb-93ef-4b70-87e3-593438fe0044] lib/mastodon/rack_middleware.rb:9:in `call'
```

### Specifications

https://github.com/nanos/mastodon/commit/2233f394e6b9c38a9c47f64e0efb9b32a5b496c9

Any advice would be greatly appreciated!

**Comment by Plastikmensch** [comment]
d1289c45f4dd47133b496fa0c28713a565a436ef removed translatable? from `app/models/status.rb` again
