### ISSUE TITLE
Custom glitch-settings cause error 

### ISSUE THREAD

**Issue by CSDUMMI** [glitch-soc/mastodon#2188]
### Steps to reproduce the problem

1. Upgrade an existing glitch database (2months old) to the current version
2. Start your server
3. Access the website
4. See a 500 error
...

### Expected behaviour

See the web app

### Actual behaviour

500 error page

### Detailed description

I think that this issue might be caused by the new custom user settings added to glitch 3 weeks ago by https://github.com/glitch-soc/mastodon/commit/3dcba94e68889f3d6603fa5416d54edd08dcf4bd?
```
mastodon-web-1  | [1cef8a5a-96b7-45a0-ae15-b1b62fce91ab] NoMethodError (undefined method `[]' for nil:NilClass):
mastodon-web-1  | [1cef8a5a-96b7-45a0-ae15-b1b62fce91ab]   
mastodon-web-1  | [1cef8a5a-96b7-45a0-ae15-b1b62fce91ab] app/models/concerns/has_user_settings.rb:63:in `setting_flavour'
mastodon-web-1  | [1cef8a5a-96b7-45a0-ae15-b1b62fce91ab] app/controllers/concerns/theming_concern.rb:14:in `current_flavour'
mastodon-web-1  | [1cef8a5a-96b7-45a0-ae15-b1b62fce91ab] app/controllers/concerns/theming_concern.rb:8:in `use_pack'
mastodon-web-1  | [1cef8a5a-96b7-45a0-ae15-b1b62fce91ab] app/controllers/concerns/web_app_controller_concern.rb:25:in `set_pack'
mastodon-web-1  | [1cef8a5a-96b7-45a0-ae15-b1b62fce91ab] app/controllers/concerns/localized.rb:11:in `set_locale'
mastodon-web-1  | [1cef8a5a-96b7-45a0-ae15-b1b62fce91ab] lib/mastodon/rack_middleware.rb:9:in `call'
mastodon-web-1  | [1cef8a5a-96b7-45a0-ae15-b1b62fce91ab] lib/public_file_server_middleware.rb:18:in `call'
```

### Specifications

Current Mastodon +Glitch +Babka on Docker

**Comment by ClearlyClaire** [comment]
Did you run migrations?
