### ISSUE TITLE
Error accessing web view

### ISSUE THREAD

**Issue by tcitworld** [glitch-soc/mastodon#2223]
### Steps to reproduce the problem

1. Checkout latest `main`, 054df2d67e61cdd78afa7b1c15fd61823c421620
2. Access any web view

### Expected behaviour

View the admin dashboard

### Actual behaviour

500 error

### Detailed description

```
bundle[750992]: [5b72dbae-9527-4509-a9f0-05e632aad463] method=GET path=/admin/dashboard format=html controller=Admin::DashboardController action=index status=500 error='ActionView::Template::Error: undefined local variable or method `settings_imports_path' for #<ActionView::Base:0x000000003fb7b8>' duration=369.84 view=0.00 db=184.36
bundle[750992]: [5b72dbae-9527-4509-a9f0-05e632aad463]
bundle[750992]: [5b72dbae-9527-4509-a9f0-05e632aad463] ActionView::Template::Error (undefined local variable or method `settings_imports_path' for #<ActionView::Base:0x000000003fb7b8>):
bundle[750992]: [5b72dbae-9527-4509-a9f0-05e632aad463]     18:               = fa_icon 'bars'
bundle[750992]: [5b72dbae-9527-4509-a9f0-05e632aad463]     19:               = fa_icon 'times'
bundle[750992]: [5b72dbae-9527-4509-a9f0-05e632aad463]     20:
bundle[750992]: [5b72dbae-9527-4509-a9f0-05e632aad463]     21:           = render_navigation
bundle[750992]: [5b72dbae-9527-4509-a9f0-05e632aad463]     22:
bundle[750992]: [5b72dbae-9527-4509-a9f0-05e632aad463]     23:     .content-wrapper
bundle[750992]: [5b72dbae-9527-4509-a9f0-05e632aad463]     24:       .content
bundle[750992]: [5b72dbae-9527-4509-a9f0-05e632aad463]
bundle[750992]: [5b72dbae-9527-4509-a9f0-05e632aad463] (eval):35:in `block (3 levels) in eval_config'
bundle[750992]: [5b72dbae-9527-4509-a9f0-05e632aad463] (eval):34:in `block (2 levels) in eval_config'
bundle[750992]: [5b72dbae-9527-4509-a9f0-05e632aad463] (eval):4:in `block in eval_config'
bundle[750992]: [5b72dbae-9527-4509-a9f0-05e632aad463] (eval):3:in `eval_config'
bundle[750992]: [5b72dbae-9527-4509-a9f0-05e632aad463] app/views/layouts/admin.html.haml:21
bundle[750992]: [5b72dbae-9527-4509-a9f0-05e632aad463] app/views/layouts/admin.html.haml:4
bundle[750992]: [5b72dbae-9527-4509-a9f0-05e632aad463] app/controllers/concerns/localized.rb:11:in `set_locale'
bundle[750992]: [5b72dbae-9527-4509-a9f0-05e632aad463] lib/mastodon/rack_middleware.rb:9:in `call'
```

### Specifications

Glitch-soc 054df2d67e61cdd78afa7b1c15fd61823c421620
Ruby 3.2.2

**Comment by tcitworld** [comment]
Gone after restart :man_shrugging:
