### ISSUE TITLE
Cannot close app setting

### ISSUE THREAD

**Issue by tribela** [glitch-soc/mastodon#2238]
### Steps to reproduce the problem

1. Getting started
2. Click App setting
3. Click "close"
...

### Expected behaviour

Close modal fine

### Actual behaviour

Cannot close modal dialog

### Detailed description

```
react-dom.development.js:3867 Uncaught TypeError: Cannot destructure property 'modalType' of '_ref' as it is undefined.
    at popModal (modal.ts:38:1)
    at modalReducer (modal.ts:81:1)
    at eval (combineReducers.js:35:1)
    at Array.forEach (<anonymous>)
    at eval (combineReducers.js:32:1)
    at Map.withMutations (immutable.es.js:1913:1)
    at eval (combineReducers.js:31:1)
    at dispatch (redux.js:258:1)
    at eval (sounds.ts:60:1)
    at eval (errors.ts:21:1)
```

### Specifications

commit fca2dff2e

**Comment by tribela** [comment]
Additionally, ESC or clicking background closes the dialog fine

**Comment by ClearlyClaire** [comment]
Hi! Thank you for your report, I can reproduce the issue and will investigate it!
