### ISSUE TITLE
Upgrade Error: Module not found: Error: Can't resolve 'locales'

### ISSUE THREAD

**Issue by horaceyoung** [glitch-soc/mastodon#2284]
### Steps to reproduce the problem

Steps to reproduce:
1. Pull from main, run bundle install & yarn install
2. Run pre-deployment database migrations
3. Run RAILS_ENV=production bundle exec rails assets:precompile
4. Will get "Can't resolve 'locales'" or "Can't resolve 'flavours/glitch/store/configureStore''

### Expected behaviour

Upgrade successfully

### Actual behaviour

Asset precompilation failure

### Detailed description

Hi all! I was trying to upgrade to v4.1.4-glitch from the latest commit of glitch-soc/main. During compilation I will always run into "Can't resolve 'locales'" or "Can't resolve 'flavours/glitch/store/configureStore'' during assets compilation. Much appreciate your help on this!

Steps to reproduce:
1. Pull from main, run bundle install & yarn install
2. Run pre-deployment database migrations
3. Run RAILS_ENV=production bundle exec rails assets:precompile
4. Will get errors

A full stack message is attached here:
```
mastodon@otter:~/live$  RAILS_ENV=production bundle exec rails assets:precompile
yarn install v1.22.19
[1/6] Validating package.json...
[2/6] Resolving packages...
[3/6] Fetching packages...
warning Pattern ["strip-ansi@^6.0.1"] is trying to unpack in the same destination "/home/mastodon/.cache/yarn/v6/npm-strip-ansi-cjs-6.0.                                 1-9e26c63d30f53443e9489495b2105d37b67a85d9-integrity/node_modules/strip-ansi-cjs" as pattern ["strip-ansi-cjs@npm:strip-ansi@^6.0.1"]. T                                 his could result in non-deterministic behavior, skipping.
warning Pattern ["string-width@^4.1.0"] is trying to unpack in the same destination "/home/mastodon/.cache/yarn/v6/npm-string-width-cjs-                                 4.2.3-269c7117d27b05ad2e536830a8ec895ef9c6d010-integrity/node_modules/string-width-cjs" as pattern ["string-width-cjs@npm:string-width@^                                 4.2.0"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["strip-ansi@^6.0.0"] is trying to unpack in the same destination "/home/mastodon/.cache/yarn/v6/npm-strip-ansi-cjs-6.0.                                 1-9e26c63d30f53443e9489495b2105d37b67a85d9-integrity/node_modules/strip-ansi-cjs" as pattern ["strip-ansi-cjs@npm:strip-ansi@^6.0.1"]. T                                 his could result in non-deterministic behavior, skipping.
warning Pattern ["string-width@^4.2.3"] is trying to unpack in the same destination "/home/mastodon/.cache/yarn/v6/npm-string-width-cjs-                                 4.2.3-269c7117d27b05ad2e536830a8ec895ef9c6d010-integrity/node_modules/string-width-cjs" as pattern ["string-width-cjs@npm:string-width@^                                 4.2.0"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["string-width@^1.0.2 || 2 || 3 || 4"] is trying to unpack in the same destination "/home/mastodon/.cache/yarn/v6/npm-st                                 ring-width-cjs-4.2.3-269c7117d27b05ad2e536830a8ec895ef9c6d010-integrity/node_modules/string-width-cjs" as pattern ["string-width-cjs@npm                                 :string-width@^4.2.0"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["string-width@^4.2.0"] is trying to unpack in the same destination "/home/mastodon/.cache/yarn/v6/npm-string-width-cjs-                                 4.2.3-269c7117d27b05ad2e536830a8ec895ef9c6d010-integrity/node_modules/string-width-cjs" as pattern ["string-width-cjs@npm:string-width@^                                 4.2.0"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["wrap-ansi@^7.0.0"] is trying to unpack in the same destination "/home/mastodon/.cache/yarn/v6/npm-wrap-ansi-cjs-7.0.0-                                 67e145cff510a6a6984bdf1152911d69d2eb9e43-integrity/node_modules/wrap-ansi-cjs" as pattern ["wrap-ansi-cjs@npm:wrap-ansi@^7.0.0"]. This c                                 ould result in non-deterministic behavior, skipping.
[4/6] Linking dependencies...
warning " > emoji-mart@3.0.1-j" has incorrect peer dependency "react@^0.14.0 || ^15.0.0-0 || ^16.0.0 || ^17.0.0".
warning " > react-motion@0.5.2" has incorrect peer dependency "react@^0.14.9 || ^15.3.0 || ^16.0.0".
warning " > react-notification@6.8.5" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning " > react-router-scroll-4@1.0.0-beta.2" has incorrect peer dependency "react@^15.0.0 || ^16.0.0".
warning " > react-router-scroll-4@1.0.0-beta.2" has incorrect peer dependency "react-dom@^15.0.0 || ^16.0.0".
warning " > react-swipeable-views@0.14.0" has incorrect peer dependency "react@^15.3.0 || ^16.0.0 || ^17.0.0".
warning "react-swipeable-views > react-swipeable-views-utils > react-event-listener@0.6.6" has incorrect peer dependency "react@^16.3.0"                                 .
warning Workspaces can only be enabled in private projects.
[5/6] Building fresh packages...
[6/6] Cleaning modules...
Done in 12.61s.
Compiling...
Compilation failed:
`isModuleDeclaration` has been deprecated, please migrate to `isImportOrExportDeclaration`
    at isModuleDeclaration (/home/mastodon/live/node_modules/@babel/types/lib/validators/generated/index.js:2740:35)
    at PluginPass.Program (/home/mastodon/live/node_modules/babel-plugin-lodash/lib/index.js:102:44)
ModuleNotFoundError: Module not found: Error: Can't resolve 'locales' in '/home/mastodon/live/app/javascript/flavours/glitch/containers'
    at /home/mastodon/live/node_modules/webpack/lib/Compilation.js:925:10
    at /home/mastodon/live/node_modules/webpack/lib/NormalModuleFactory.js:401:22
    at /home/mastodon/live/node_modules/webpack/lib/NormalModuleFactory.js:130:21
    at /home/mastodon/live/node_modules/webpack/lib/NormalModuleFactory.js:224:22
    at /home/mastodon/live/node_modules/neo-async/async.js:2830:7
    at /home/mastodon/live/node_modules/neo-async/async.js:6877:13
    at /home/mastodon/live/node_modules/webpack/lib/NormalModuleFactory.js:214:25
    at /home/mastodon/live/node_modules/enhanced-resolve/lib/Resolver.js:213:14
    at /home/mastodon/live/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/mastodon/live/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /home/mastodon/live/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
    at /home/mastodon/live/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/mastodon/live/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /home/mastodon/live/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/mastodon/live/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /home/mastodon/live/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
    at /home/mastodon/live/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/mastodon/live/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:43:1)
    at /home/mastodon/live/node_modules/enhanced-resolve/lib/ModuleKindPlugin.js:30:40
    at /home/mastodon/live/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/mastodon/live/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /home/mastodon/live/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/mastodon/live/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /home/mastodon/live/node_modules/enhanced-resolve/lib/forEachBail.js:30:14
    at /home/mastodon/live/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/mastodon/live/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /home/mastodon/live/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
    at /home/mastodon/live/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/mastodon/live/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /home/mastodon/live/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/mastodon/live/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /home/mastodon/live/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/mastodon/live/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /home/mastodon/live/node_modules/enhanced-resolve/lib/RootPlugin.js:37:38
    at _next42 (eval at create (/home/mastodon/live/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:8:1)
    at eval (eval at create (/home/mastodon/live/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:31:1)
    at /home/mastodon/live/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/mastodon/live/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /home/mastodon/live/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/mastodon/live/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /home/mastodon/live/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/mastodon/live/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /home/mastodon/live/node_modules/enhanced-resolve/lib/DirectoryExistsPlugin.js:27:15
    at /home/mastodon/live/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:85:15
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
resolve 'locales' in '/home/mastodon/live/app/javascript/flavours/glitch/containers'
  Parsed request is a module
  using description file: /home/mastodon/live/package.json (relative path: ./app/javascript/flavours/glitch/containers)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      looking for modules in /home/mastodon/live/app/javascript
        using description file: /home/mastodon/live/package.json (relative path: ./app/javascript)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: /home/mastodon/live/package.json (relative path: ./app/javascript/locales)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /home/mastodon/live/app/javascript/locales doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              /home/mastodon/live/app/javascript/locales.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /home/mastodon/live/app/javascript/locales.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/mastodon/live/app/javascript/locales.jsx doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /home/mastodon/live/app/javascript/locales.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/mastodon/live/app/javascript/locales.tsx doesn't exist
            .sass
              Field 'browser' doesn't contain a valid alias configuration
              /home/mastodon/live/app/javascript/locales.sass doesn't exist
            .scss
              Field 'browser' doesn't contain a valid alias configuration
              /home/mastodon/live/app/javascript/locales.scss doesn't exist
            .css
              Field 'browser' doesn't contain a valid alias configuration
              /home/mastodon/live/app/javascript/locales.css doesn't exist
            .module.sass
              Field 'browser' doesn't contain a valid alias configuration
              /home/mastodon/live/app/javascript/locales.module.sass doesn't exist
            .module.scss
              Field 'browser' doesn't contain a valid alias configuration
              /home/mastodon/live/app/javascript/locales.module.scss doesn't exist
            .module.css
              Field 'browser' doesn't contain a valid alias configuration
              /home/mastodon/live/app/javascript/locales.module.css doesn't exist
            .png
              Field 'browser' doesn't contain a valid alias configuration
              /home/mastodon/live/app/javascript/locales.png doesn't exist
            .svg
              Field 'browser' doesn't contain a valid alias configuration
              /home/mastodon/live/app/javascript/locales.svg doesn't exist
            .gif
              Field 'browser' doesn't contain a valid alias configuration
              /home/mastodon/live/app/javascript/locales.gif doesn't exist
            .jpeg
              Field 'browser' doesn't contain a valid alias configuration
              /home/mastodon/live/app/javascript/locales.jpeg doesn't exist
            .jpg
              Field 'browser' doesn't contain a valid alias configuration
              /home/mastodon/live/app/javascript/locales.jpg doesn't exist
            as directory
              /home/mastodon/live/app/javascript/locales doesn't exist
      /home/mastodon/live/app/javascript/flavours/glitch/containers/node_modules doesn't exist or is not a directory
      /home/mastodon/live/app/javascript/flavours/glitch/node_modules doesn't exist or is not a directory
      /home/mastodon/live/app/javascript/flavours/node_modules doesn't exist or is not a directory
      /home/mastodon/live/app/javascript/node_modules doesn't exist or is not a directory
      /home/mastodon/live/app/node_modules doesn't exist or is not a directory
      /home/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /home/mastodon/live/node_modules
        using description file: /home/mastodon/live/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
      looking for modules in /home/mastodon/node_modules
        No description file found
        Field 'browser' doesn't contain a valid alias configuration
          using description file: /home/mastodon/live/package.json (relative path: ./node_modules/locales)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /home/mastodon/live/node_modules/locales doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              /home/mastodon/live/node_modules/locales.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
        No description file found
        no extension
          Field 'browser' doesn't contain a valid alias configuration
              /home/mastodon/live/node_modules/locales.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
          /home/mastodon/node_modules/locales doesn't exist
        .mjs
          Field 'browser' doesn't contain a valid alias configuration
              /home/mastodon/live/node_modules/locales.jsx doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
          /home/mastodon/node_modules/locales.mjs doesn't exist
        .js
          Field 'browser' doesn't contain a valid alias configuration
              /home/mastodon/live/node_modules/locales.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
          /home/mastodon/node_modules/locales.js doesn't exist
        .jsx
          Field 'browser' doesn't contain a valid alias configuration
              /home/mastodon/live/node_modules/locales.tsx doesn't exist
            .sass
              Field 'browser' doesn't contain a valid alias configuration
          /home/mastodon/node_modules/locales.jsx doesn't exist
        .ts
          Field 'browser' doesn't contain a valid alias configuration
              /home/mastodon/live/node_modules/locales.sass doesn't exist
            .scss
              Field 'browser' doesn't contain a valid alias configuration
          /home/mastodon/node_modules/locales.ts doesn't exist
        .tsx
          Field 'browser' doesn't contain a valid alias configuration
              /home/mastodon/live/node_modules/locales.scss doesn't exist
            .css
              Field 'browser' doesn't contain a valid alias configuration
          /home/mastodon/node_modules/locales.tsx doesn't exist
        .sass
          Field 'browser' doesn't contain a valid alias configuration
              /home/mastodon/live/node_modules/locales.css doesn't exist
            .module.sass
              Field 'browser' doesn't contain a valid alias configuration
          /home/mastodon/node_modules/locales.sass doesn't exist
        .scss
          Field 'browser' doesn't contain a valid alias configuration
              /home/mastodon/live/node_modules/locales.module.sass doesn't exist
            .module.scss
              Field 'browser' doesn't contain a valid alias configuration
          /home/mastodon/node_modules/locales.scss doesn't exist
        .css
          Field 'browser' doesn't contain a valid alias configuration
              /home/mastodon/live/node_modules/locales.module.scss doesn't exist
            .module.css
              Field 'browser' doesn't contain a valid alias configuration
          /home/mastodon/node_modules/locales.css doesn't exist
        .module.sass
          Field 'browser' doesn't contain a valid alias configuration
              /home/mastodon/live/node_modules/locales.module.css doesn't exist
            .png
              Field 'browser' doesn't contain a valid alias configuration
          /home/mastodon/node_modules/locales.module.sass doesn't exist
        .module.scss
          Field 'browser' doesn't contain a valid alias configuration
              /home/mastodon/live/node_modules/locales.png doesn't exist
            .svg
              Field 'browser' doesn't contain a valid alias configuration
          /home/mastodon/node_modules/locales.module.scss doesn't exist
        .module.css
          Field 'browser' doesn't contain a valid alias configuration
              /home/mastodon/live/node_modules/locales.svg doesn't exist
            .gif
              Field 'browser' doesn't contain a valid alias configuration
          /home/mastodon/node_modules/locales.module.css doesn't exist
        .png
          Field 'browser' doesn't contain a valid alias configuration
              /home/mastodon/live/node_modules/locales.gif doesn't exist
            .jpeg
              Field 'browser' doesn't contain a valid alias configuration
          /home/mastodon/node_modules/locales.png doesn't exist
        .svg
          Field 'browser' doesn't contain a valid alias configuration
              /home/mastodon/live/node_modules/locales.jpeg doesn't exist
            .jpg
              Field 'browser' doesn't contain a valid alias configuration
          /home/mastodon/node_modules/locales.svg doesn't exist
        .gif
          Field 'browser' doesn't contain a valid alias configuration
              /home/mastodon/live/node_modules/locales.jpg doesn't exist
          /home/mastodon/node_modules/locales.gif doesn't exist
        .jpeg
          Field 'browser' doesn't contain a valid alias configuration
            as directory
              /home/mastodon/live/node_modules/locales doesn't exist
          /home/mastodon/node_modules/locales.jpeg doesn't exist
        .jpg
          Field 'browser' doesn't contain a valid alias configuration
          /home/mastodon/node_modules/locales.jpg doesn't exist
        as directory
          /home/mastodon/node_modules/locales doesn't exist
```

### Specifications

ruby 3.0.6p216
rbenv 1.2.0-52-g61747c0
node v16.20.1
Bundler version 2.2.33
yarn 1.22.19

**Comment by ClearlyClaire** [comment]
Hi, do you have any local change?

**Comment by horaceyoung** [comment]
> 

Hi I stashed all local changes. There shouldn't be any

**Comment by ClearlyClaire** [comment]
Do you perhaps have extra files under `app`?

**Comment by horaceyoung** [comment]
> 

There are some untracked files. Let me clean them and retry

**Comment by horaceyoung** [comment]
Thank you so much! After adding and stashing untracked files the pre-compilation was successful
