### ISSUE TITLE
can't cast Array (TypeError) while removing statuses

### ISSUE THREAD

**Issue by tcitworld** [glitch-soc/mastodon#2329]
### Steps to reproduce the problem

1.  Simply run `bin/tootctl statuses remove`

### Expected behaviour

Process done properly

### Actual behaviour

Error thrown

### Detailed description

```
bin/tootctl statuses remove                                                                                       
Creating temporary database indices...
Extract the deletion target from statuses... This might take a while...                                                                                       
Removing temporary database indices to restore write performance...
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/abstract/quoting.rb:43:in `type_cast': can't cast Array (TypeError)
                                                                                                                                                              
        else raise TypeError, "can't cast #{value.class.name}"
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/postgresql/quoting.rb:142:in `type_cast'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/abstract/quoting.rb:220:in `block in type_casted_binds'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/abstract/quoting.rb:216:in `map'       
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/abstract/quoting.rb:216:in `type_casted_binds'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/postgresql_adapter.rb:765:in `exec_no_cache'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/postgresql_adapter.rb:745:in `execute_and_clear'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/postgresql/database_statements.rb:54:in `exec_query'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/abstract/database_statements.rb:132:in `exec_insert'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/postgresql/database_statements.rb:88:in `exec_insert'
        from /home/mastodon/live/lib/mastodon/cli/statuses.rb:64:in `remove_statuses'
        from /home/mastodon/live/lib/mastodon/cli/statuses.rb:34:in `remove'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'                                                        
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:116:in `invoke'                                               
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor.rb:243:in `block in subcommand'                                             
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'                                                      
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'                                       
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'                                                        
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'                                                      
        from bin/tootctl:9:in `block in <main>'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/chewy-7.3.3/lib/chewy/strategy.rb:60:in `wrap'                                                  
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/chewy-7.3.3/lib/chewy.rb:154:in `strategy'                                                      
        from bin/tootctl:8:in `<main>'  
```

### Specifications

Mastodon version `4.1.4+glitch`  cf9affdeac275cd4057dc57c3b16bf4fa5e9405a
Ruby version 3.2.2
PostgreSQL 13.11

**Comment by Plastikmensch** [comment]
Unfortunately an upstream issue and there is already an issue filed for this upstream.

**Comment by tcitworld** [comment]
Oh, I didn't found it when posting. https://github.com/mastodon/mastodon/issues/26171 is the one for reference.
