### ISSUE TITLE
NoMethodError on preview_card

### ISSUE THREAD

**Issue by Tyketc** [glitch-soc/mastodon#2533]
### Steps to reproduce the problem

1. check out f425a1e6378bd4fbed568100f0c26acfc6db8fd9 and setup server
2. visit `/home` or get home timeline (preferably one of the status lists should include a link with preview_card）
3. see 500 error (log is in detailed description)

### Expected behaviour

Home timeline loads successfully

### Actual behaviour

NoMethodError on preview_card

### Detailed description

Log:
```
mastodon-web        | I, [2023-12-21T02:11:11.735503 #19]  INFO -- : [9be518f8-4a29-4763-b2d8-5e61effdd602] method=GET path=/api/v1/markers format=html controller=Api::V1::MarkersController action=index status=200 allocations=15416 duration=41.05 view=0.90 db=17.84
mastodon-web        | I, [2023-12-21T02:11:11.851549 #11]  INFO -- : [92062055-6771-441e-a53f-659a35d6b445] method=GET path=/api/v1/timelines/home format=html controller=Api::V1::Timelines::HomeController action=show status=500 allocations=61947 duration=159.75 view=0.00 db=36.28
mastodon-web        | F, [2023-12-21T02:11:11.852773 #11] FATAL -- : [92062055-6771-441e-a53f-659a35d6b445]   
mastodon-web        | [92062055-6771-441e-a53f-659a35d6b445] NoMethodError (undefined method `url' for #<PreviewCardsStatus preview_card_id: 3698, status_id: 111585222622568163>):
mastodon-web        | [92062055-6771-441e-a53f-659a35d6b445]   
mastodon-web        | [92062055-6771-441e-a53f-659a35d6b445] app/models/status.rb:237:in `block in preview_card'
mastodon-web        | [92062055-6771-441e-a53f-659a35d6b445] app/models/status.rb:237:in `preview_card'
mastodon-web        | [92062055-6771-441e-a53f-659a35d6b445] app/controllers/api/v1/timelines/home_controller.rb:15:in `show'
mastodon-web        | [92062055-6771-441e-a53f-659a35d6b445] app/controllers/concerns/localized.rb:11:in `set_locale'
mastodon-web        | [92062055-6771-441e-a53f-659a35d6b445] lib/mastodon/rack_middleware.rb:9:in `call'
mastodon-web        | [92062055-6771-441e-a53f-659a35d6b445] lib/public_file_server_middleware.rb:18:in `call'
mastodon-web        | I, [2023-12-21T02:11:12.134351 #19]  INFO -- : [50a3d4eb-e059-40d0-8b1c-918e35ca88fe] method=GET path=/api/v1/notifications format=html controller=Api::V1::NotificationsController action=index status=500 allocations=199097 duration=437.32 view=0.00 db=59.66
mastodon-web        | F, [2023-12-21T02:11:12.135491 #19] FATAL -- : [50a3d4eb-e059-40d0-8b1c-918e35ca88fe]   
mastodon-web        | [50a3d4eb-e059-40d0-8b1c-918e35ca88fe] NoMethodError (undefined method `url' for #<PreviewCardsStatus preview_card_id: 2898, status_id: 111328903592875068>):
mastodon-web        | [50a3d4eb-e059-40d0-8b1c-918e35ca88fe]   
mastodon-web        | [50a3d4eb-e059-40d0-8b1c-918e35ca88fe] app/models/status.rb:237:in `block in preview_card'
mastodon-web        | [50a3d4eb-e059-40d0-8b1c-918e35ca88fe] app/models/status.rb:237:in `preview_card'
mastodon-web        | [50a3d4eb-e059-40d0-8b1c-918e35ca88fe] app/controllers/api/v1/notifications_controller.rb:17:in `index'
mastodon-web        | [50a3d4eb-e059-40d0-8b1c-918e35ca88fe] app/controllers/concerns/localized.rb:11:in `set_locale'
mastodon-web        | [50a3d4eb-e059-40d0-8b1c-918e35ca88fe] lib/mastodon/rack_middleware.rb:9:in `call'
mastodon-web        | [50a3d4eb-e059-40d0-8b1c-918e35ca88fe] lib/public_file_server_middleware.rb:18:in `call'
```

### Mastodon version

v4.3.0-alpha.0+glitch (f425a1e63)

**Comment by ClearlyClaire** [comment]
Did you perhaps forget to run the database migrations before restarting Mastodon services?

**Comment by Tyketc** [comment]
Oops, sorry... I forgot again 😳
