### ISSUE TITLE
"rails assets:precompile" error on "nightly.2024-03-01"

### ISSUE THREAD

**Issue by jippi** [glitch-soc/mastodon#2658]
### Steps to reproduce the problem

NOTE: This worked on `nightly.2024-02-29` and all releases before it

In my `Dockerfile` (using `FROM ghcr.io/glitch-soc/mastodon:${RELEASE}` I have the following

```sh
RUN OTP_SECRET=precompile_placeholder SECRET_KEY_BASE=precompile_placeholder bundle exec rails assets:precompile 
```

and it fails with the following error when building

```sh
#25 0.093 + bundle exec rails assets:precompile
#25 3.342 Compiling...
#25 36.22 Compilation failed:
#25 36.22 ModuleNotFoundError: Module not found: Error: Can't resolve '/opt/mastodon/app/javascript/packs/admin.jsx' in '/opt/mastodon'
#25 36.22     at /opt/mastodon/node_modules/webpack/lib/Compilation.js:925:10
#25 36.22     at /opt/mastodon/node_modules/webpack/lib/NormalModuleFactory.js:401:22
#25 36.22     at /opt/mastodon/node_modules/webpack/lib/NormalModuleFactory.js:130:21
#25 36.22     at /opt/mastodon/node_modules/webpack/lib/NormalModuleFactory.js:224:22
#25 36.22     at /opt/mastodon/node_modules/neo-async/async.js:2830:7
#25 36.22     at /opt/mastodon/node_modules/neo-async/async.js:6877:13
#25 36.22     at /opt/mastodon/node_modules/webpack/lib/NormalModuleFactory.js:214:25
#25 36.22     at /opt/mastodon/node_modules/enhanced-resolve/lib/Resolver.js:213:14
#25 36.22     at /opt/mastodon/node_modules/enhanced-resolve/lib/Resolver.js:285:5
#25 36.22     at eval (eval at create (/opt/mastodon/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
#25 36.22     at /opt/mastodon/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
#25 36.22     at /opt/mastodon/node_modules/enhanced-resolve/lib/Resolver.js:285:5
#25 36.22     at eval (eval at create (/opt/mastodon/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
#25 36.22     at /opt/mastodon/node_modules/enhanced-resolve/lib/Resolver.js:285:5
#25 36.22     at eval (eval at create (/opt/mastodon/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
#25 36.22     at /opt/mastodon/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
#25 36.22     at /opt/mastodon/node_modules/enhanced-resolve/lib/Resolver.js:285:5
#25 36.22     at eval (eval at create (/opt/mastodon/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
#25 36.22     at /opt/mastodon/node_modules/enhanced-resolve/lib/RootPlugin.js:60:9
#25 36.22     at /opt/mastodon/node_modules/enhanced-resolve/lib/Resolver.js:285:5
#25 36.22     at eval (eval at create (/opt/mastodon/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
#25 36.22     at /opt/mastodon/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
#25 36.22     at /opt/mastodon/node_modules/enhanced-resolve/lib/Resolver.js:285:5
#25 36.22     at eval (eval at create (/opt/mastodon/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
#25 36.22     at /opt/mastodon/node_modules/enhanced-resolve/lib/Resolver.js:285:5
#25 36.22     at eval (eval at create (/opt/mastodon/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
#25 36.22     at /opt/mastodon/node_modules/enhanced-resolve/lib/DirectoryExistsPlugin.js:27:15
#25 36.22     at /opt/mastodon/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:85:15
#25 36.22     at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
#25 36.22 resolve '/opt/mastodon/app/javascript/packs/admin.jsx' in '/opt/mastodon'
#25 36.22   using description file: /opt/mastodon/package.json (relative path: .)
#25 36.22     Field 'browser' doesn't contain a valid alias configuration
#25 36.22     using description file: /opt/mastodon/package.json (relative path: ./app/javascript/packs/admin.jsx)
#25 36.22       no extension
#25 36.22         Field 'browser' doesn't contain a valid alias configuration
#25 36.22         /opt/mastodon/app/javascript/packs/admin.jsx doesn't exist
#25 36.22       .mjs
#25 36.22         Field 'browser' doesn't contain a valid alias configuration
#25 36.22         /opt/mastodon/app/javascript/packs/admin.jsx.mjs doesn't exist
#25 36.22       .js
#25 36.22         Field 'browser' doesn't contain a valid alias configuration
#25 36.22         /opt/mastodon/app/javascript/packs/admin.jsx.js doesn't exist
#25 36.22       .jsx
#25 36.22         Field 'browser' doesn't contain a valid alias configuration
#25 36.22         /opt/mastodon/app/javascript/packs/admin.jsx.jsx doesn't exist
#25 36.22       .ts
#25 36.22         Field 'browser' doesn't contain a valid alias configuration
#25 36.22         /opt/mastodon/app/javascript/packs/admin.jsx.ts doesn't exist
#25 36.22       .tsx
#25 36.22         Field 'browser' doesn't contain a valid alias configuration
#25 36.22         /opt/mastodon/app/javascript/packs/admin.jsx.tsx doesn't exist
#25 36.22       .sass
#25 36.22         Field 'browser' doesn't contain a valid alias configuration
#25 36.22         /opt/mastodon/app/javascript/packs/admin.jsx.sass doesn't exist
#25 36.22       .scss
#25 36.22         Field 'browser' doesn't contain a valid alias configuration
#25 36.22         /opt/mastodon/app/javascript/packs/admin.jsx.scss doesn't exist
#25 36.22       .css
#25 36.22         Field 'browser' doesn't contain a valid alias configuration
#25 36.22         /opt/mastodon/app/javascript/packs/admin.jsx.css doesn't exist
#25 36.22       .module.sass
#25 36.22         Field 'browser' doesn't contain a valid alias configuration
#25 36.22         /opt/mastodon/app/javascript/packs/admin.jsx.module.sass doesn't exist
#25 36.22       .module.scss
#25 36.22         Field 'browser' doesn't contain a valid alias configuration
#25 36.22         /opt/mastodon/app/javascript/packs/admin.jsx.module.scss doesn't exist
#25 36.22       .module.css
#25 36.22         Field 'browser' doesn't contain a valid alias configuration
#25 36.22         /opt/mastodon/app/javascript/packs/admin.jsx.module.css doesn't exist
#25 36.22       .png
#25 36.22         Field 'browser' doesn't contain a valid alias configuration
#25 36.22         /opt/mastodon/app/javascript/packs/admin.jsx.png doesn't exist
#25 36.22       .svg
#25 36.22         Field 'browser' doesn't contain a valid alias configuration
#25 36.22         /opt/mastodon/app/javascript/packs/admin.jsx.svg doesn't exist
#25 36.22       .gif
#25 36.22         Field 'browser' doesn't contain a valid alias configuration
#25 36.22         /opt/mastodon/app/javascript/packs/admin.jsx.gif doesn't exist
#25 36.22       .jpeg
#25 36.22         Field 'browser' doesn't contain a valid alias configuration
#25 36.22         /opt/mastodon/app/javascript/packs/admin.jsx.jpeg doesn't exist
#25 36.22       .jpg
#25 36.22         Field 'browser' doesn't contain a valid alias configuration
#25 36.22         /opt/mastodon/app/javascript/packs/admin.jsx.jpg doesn't exist
#25 36.22       as directory
#25 36.22         /opt/mastodon/app/javascript/packs/admin.jsx doesn't exist
#25 36.22     root path /opt/mastodon
#25 36.22       using description file: /opt/mastodon/package.json (relative path: ./opt/mastodon/app/javascript/packs/admin.jsx)
#25 36.22         no extension
#25 36.22           Field 'browser' doesn't contain a valid alias configuration
#25 36.22           /opt/mastodon/opt/mastodon/app/javascript/packs/admin.jsx doesn't exist
#25 36.22         .mjs
#25 36.22           Field 'browser' doesn't contain a valid alias configuration
#25 36.22           /opt/mastodon/opt/mastodon/app/javascript/packs/admin.jsx.mjs doesn't exist
#25 36.22         .js
#25 36.22           Field 'browser' doesn't contain a valid alias configuration
#25 36.22           /opt/mastodon/opt/mastodon/app/javascript/packs/admin.jsx.js doesn't exist
#25 36.22         .jsx
#25 36.22           Field 'browser' doesn't contain a valid alias configuration
#25 36.22           /opt/mastodon/opt/mastodon/app/javascript/packs/admin.jsx.jsx doesn't exist
#25 36.22         .ts
#25 36.22           Field 'browser' doesn't contain a valid alias configuration
#25 36.22           /opt/mastodon/opt/mastodon/app/javascript/packs/admin.jsx.ts doesn't exist
#25 36.22         .tsx
#25 36.22           Field 'browser' doesn't contain a valid alias configuration
#25 36.22           /opt/mastodon/opt/mastodon/app/javascript/packs/admin.jsx.tsx doesn't exist
#25 36.22         .sass
#25 36.22           Field 'browser' doesn't contain a valid alias configuration
#25 36.22           /opt/mastodon/opt/mastodon/app/javascript/packs/admin.jsx.sass doesn't exist
#25 36.22         .scss
#25 36.22           Field 'browser' doesn't contain a valid alias configuration
#25 36.22           /opt/mastodon/opt/mastodon/app/javascript/packs/admin.jsx.scss doesn't exist
#25 36.22         .css
#25 36.22           Field 'browser' doesn't contain a valid alias configuration
#25 36.22           /opt/mastodon/opt/mastodon/app/javascript/packs/admin.jsx.css doesn't exist
#25 36.22         .module.sass
#25 36.22           Field 'browser' doesn't contain a valid alias configuration
#25 36.22           /opt/mastodon/opt/mastodon/app/javascript/packs/admin.jsx.module.sass doesn't exist
#25 36.22         .module.scss
#25 36.22           Field 'browser' doesn't contain a valid alias configuration
#25 36.22           /opt/mastodon/opt/mastodon/app/javascript/packs/admin.jsx.module.scss doesn't exist
#25 36.22         .module.css
#25 36.22           Field 'browser' doesn't contain a valid alias configuration
#25 36.22           /opt/mastodon/opt/mastodon/app/javascript/packs/admin.jsx.module.css doesn't exist
#25 36.22         .png
#25 36.22           Field 'browser' doesn't contain a valid alias configuration
#25 36.22           /opt/mastodon/opt/mastodon/app/javascript/packs/admin.jsx.png doesn't exist
#25 36.22         .svg
#25 36.22           Field 'browser' doesn't contain a valid alias configuration
#25 36.22           /opt/mastodon/opt/mastodon/app/javascript/packs/admin.jsx.svg doesn't exist
#25 36.22         .gif
#25 36.22           Field 'browser' doesn't contain a valid alias configuration
#25 36.22           /opt/mastodon/opt/mastodon/app/javascript/packs/admin.jsx.gif doesn't exist
#25 36.22         .jpeg
#25 36.22           Field 'browser' doesn't contain a valid alias configuration
#25 36.22           /opt/mastodon/opt/mastodon/app/javascript/packs/admin.jsx.jpeg doesn't exist
#25 36.22         .jpg
#25 36.22           Field 'browser' doesn't contain a valid alias configuration
#25 36.22           /opt/mastodon/opt/mastodon/app/javascript/packs/admin.jsx.jpg doesn't exist
#25 36.22         as directory
#25 36.22           /opt/mastodon/opt/mastodon/app/javascript/packs/admin.jsx doesn't exist
#25 36.22 
```

### Expected behaviour

build succeeds

### Actual behaviour

build fails

### Mastodon instance

expressional.social

### Mastodon version

nightly.2024-03-01

### Browser name and version

N/A

### Operating system

N/A

**Comment by ClearlyClaire** [comment]
I'm a bit confused by your setup, and can't reproduce the issue. There shouldn't be any reason for the build process to look up `admin.jsx` anymore (this has been moved to `admin.tsx`). Do you have any local change?
