### ISSUE TITLE
Incompatibility with OpenSearch

### ISSUE THREAD

**Issue by NoaHimesaka1873** [glitch-soc/mastodon#2707]
### Steps to reproduce the problem

1. Open Admin panel
2. ???
3. ERROR!

### Expected behaviour

Opened page

### Actual behaviour

Error page

### Detailed description

Caused by Elasticsearch's attempt to sabotage OpenSearch users

### Mastodon instance

toot.funami.tech

### Mastodon version

v4.3.0-alpha.3+YRYRi

### Browser name and version

Firefox 125.0.3 

### Operating system

Arch Linux

### Technical details

```
web-1  | [REDACTED] Elasticsearch::UnsupportedProductError (The client noticed that the server is not Elasticsearch and we do not support this unknown product.):
web-1  | [REDACTED]   
web-1  | [REDACTED] app/lib/admin/system_check/elasticsearch_check.rb:64:in `running_version'
web-1  | [REDACTED] app/lib/admin/system_check/elasticsearch_check.rb:19:in `pass?'
web-1  | [REDACTED] app/lib/admin/system_check.rb:17:in `block in perform'
web-1  | [REDACTED] app/lib/admin/system_check.rb:14:in `each'
web-1  | [REDACTED] app/lib/admin/system_check.rb:14:in `each_with_object'
web-1  | [REDACTED] app/lib/admin/system_check.rb:14:in `perform'
web-1  | [REDACTED] app/controllers/admin/dashboard_controller.rb:10:in `index'
web-1  | [REDACTED] app/controllers/concerns/localized.rb:11:in `set_locale'
web-1  | [REDACTED] lib/mastodon/rack_middleware.rb:9:in `call'
web-1  | [REDACTED] lib/public_file_server_middleware.rb:18:in `call'
```

**Comment by ClearlyClaire** [comment]
Yeah, this is an unintended effect of updating our Elasticsearch client library. We will have a look.

**Comment by ClearlyClaire** [comment]
This should now be fixed!

**Comment by NoaHimesaka1873** [comment]
Great! Thanks for the quick fix!
