### ISSUE TITLE
Suspend not working

### ISSUE THREAD

**Issue by NoaHimesaka1873** [glitch-soc/mastodon#2862]
### Steps to reproduce the problem

1. Suspend

### Expected behaviour

Gets suspended

### Actual behaviour

Error

### Detailed description

```
web-1                | [82f06969-79d0-4272-9a8b-73140be6b800] NoMethodError (undefined method `will_save_change_to_attribution_domains?' for an instance of Account):
web-1                | [82f06969-79d0-4272-9a8b-73140be6b800]
web-1                | [82f06969-79d0-4272-9a8b-73140be6b800] app/models/concerns/account/attribution_domains.rb:7:in `block (2 levels) in <module:AttributionDomains>'
web-1                | [82f06969-79d0-4272-9a8b-73140be6b800] app/models/account.rb:280:in `block in suspend!'
web-1                | [82f06969-79d0-4272-9a8b-73140be6b800] app/models/account.rb:278:in `suspend!'
web-1                | [82f06969-79d0-4272-9a8b-73140be6b800] app/models/form/account_batch.rb:114:in `reject_account'
web-1                | [82f06969-79d0-4272-9a8b-73140be6b800] app/models/form/account_batch.rb:90:in `block in suspend!'
web-1                | [82f06969-79d0-4272-9a8b-73140be6b800] app/models/form/account_batch.rb:88:in `suspend!'
web-1                | [82f06969-79d0-4272-9a8b-73140be6b800] app/models/form/account_batch.rb:31:in `save'
web-1                | [82f06969-79d0-4272-9a8b-73140be6b800] app/controllers/admin/accounts_controller.rb:24:in `batch'
web-1                | [82f06969-79d0-4272-9a8b-73140be6b800] app/controllers/concerns/localized.rb:11:in `set_locale'
web-1                | [82f06969-79d0-4272-9a8b-73140be6b800] lib/mastodon/rack_middleware.rb:9:in `call'
web-1                | [82f06969-79d0-4272-9a8b-73140be6b800] lib/public_file_server_middleware.rb:18:in `call'
```

### Mastodon instance

toot.funami.tech

### Mastodon version

v4.3.0-rc.1+YRYRi

### Browser name and version

Safari

### Operating system

macOS 15.1 DB

### Technical details

My instance does run customised fork, but I didn't touch any code that handles suspend part so in theory it should not matter. It's using latest commit from glitch-soc. Still would be best idea to check if it's reproducible on glitch-soc but I don't have any test instance to do so.

**Comment by ClearlyClaire** [comment]
Hi! Please make sure you ran database migrations then restarted Mastodon services.

**Comment by NoaHimesaka1873** [comment]
> Hi! Please make sure you ran database migrations then restarted Mastodon services.

I did run database migration but forgot restarting! And it works now, dumb me! Closing the issue.
