### ISSUE TITLE
Regression: Regex metachars can break the FeedInsertWorker

### ISSUE THREAD

**Issue by monsterpit-daggertooth** [glitch-soc/mastodon#533]
As of commit f009fef, Regex metachars such as unmatched parentheses can cause the FeedInsertWorker to break.

<details>
<summary>Sidekiq log</summary>

```
2018-06-05T03:51:27.614Z 20559 TID-oxdswr9t3 WARN: {"context":"Job raised exception","job":{"class":"FeedInsertWorker","args":[100149566514466936,1,"home"],"retry":true,"queue":"default","jid":"d40795ca75c94abe0931dfcf","created_at":1528161110.1875865,"enqueued_at":1528170687.6089418,"error_message":"end pattern with unmatched parenthesis: /(--/i","error_class":"RegexpError","failed_at":1528161110.231477,"retry_count":8,"retried_at":1528166546.1584256},"jobstr":"{\"class\":\"FeedInsertWorker\",\"args\":[100149566514466936,1,\"home\"],\"retry\":true,\"queue\":\"default\",\"jid\":\"d40795ca75c94abe0931dfcf\",\"created_at\":1528161110.1875865,\"enqueued_at\":1528170687.6089418,\"error_message\":\"end pattern with unmatched parenthesis: /(--/i\",\"error_class\":\"RegexpError\",\"failed_at\":1528161110.231477,\"retry_count\":8,\"retried_at\":1528166546.1584256}"}
2018-06-05T03:51:27.614Z 20559 TID-oxdswr9t3 WARN: RegexpError: end pattern with unmatched parenthesis: /(--/i
2018-06-05T03:51:27.614Z 20559 TID-oxdswr9t3 WARN: /var/lib/mastodon/live/app/models/glitch/keyword_mute.rb:53:in `matches?'
/var/lib/mastodon/live/app/models/glitch/keyword_mute.rb:85:in `block in matches?'
/var/lib/mastodon/live/app/models/glitch/keyword_mute.rb:85:in `any?'
/var/lib/mastodon/live/app/models/glitch/keyword_mute.rb:85:in `matches?'
/var/lib/mastodon/live/app/models/glitch/keyword_mute_helper.rb:19:in `matchers_match?'
/var/lib/mastodon/live/app/models/glitch/keyword_mute_helper.rb:13:in `matches?'
/var/lib/mastodon/live/app/lib/feed_manager.rb:187:in `keyword_filter?'
/var/lib/mastodon/live/app/lib/feed_manager.rb:156:in `filter_from_home?'
/var/lib/mastodon/live/app/lib/feed_manager.rb:21:in `filter?'
/var/lib/mastodon/live/app/workers/feed_insert_worker.rb:32:in `feed_filtered?'
/var/lib/mastodon/live/app/workers/feed_insert_worker.rb:26:in `check_and_insert'
/var/lib/mastodon/live/app/workers/feed_insert_worker.rb:18:in `perform'
[~snip~]
```

</details>

**Comment by yipdw** [comment]
Argh.  This is why I probably should have done https://github.com/glitch-soc/mastodon/issues/463 first.

Thanks for the report.  If you get some time to port #458 before I do (which is likely), please also consider adding an example to the spec suite so I don't screw this up again.

**Comment by yipdw** [comment]
I think https://github.com/glitch-soc/mastodon/commit/a640c322c19013647cbd19ac907dd18b57c2b1b8 on the `restructure-kw-as-word-lists` branch addresses this problem.  Can you try that out and report back whether it solves the problems you're running into? If so, I'll merge it to master.

**Comment by monsterpit-daggertooth** [comment]
Working 💯 👍 .

**Comment by yipdw** [comment]
Cool, thanks for the feedback.  I'll merge it to master.
