### ISSUE TITLE
Cant update yarn (node-gyp fails)

### ISSUE THREAD

**Issue by magicalraccoon** [glitch-soc/mastodon#827]
I'm trying to update my instance following the [Updating Mastodon](https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Updating-Mastodon-Guide.md) documentation and I've run into a problem. Is there a way to bypass this?

```

$ yarn install --pure-lockfile

yarn install v1.12.3
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.0.14: The platform "linux" is incompatible with this module.
info "fsevents@1.0.14" is an optional dependency and failed compatibility check. Excluding it from installation.
warning store@1.3.20: The engine "browser" appears to be invalid.
[3/4] Linking dependencies...
warning " > chai-enzyme@0.6.1" has unmet peer dependency "cheerio@0.19.x || 0.20.x || 0.22.x".
warning " > react-decoration@1.4.0" has incorrect peer dependency "react-addons-perf@15.3.2".
warning " > react-redux-loading-bar@2.4.1" has incorrect peer dependency "react-redux@^3.0.0 || ^4.0.0".
warning " > react-storybook-addon-intl@0.1.0" has incorrect peer dependency "@kadira/storybook@^1.35.1".
[4/4] Building fresh packages...
[1/3] ⢀ bufferutil
[2/3] ⢀ node-sass
error /home/mastodon/live/node_modules/node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments: 
Directory: /home/mastodon/live/node_modules/node-sass
Output:
Building: /usr/bin/node /home/mastodon/live/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/bin/node',
gyp verb cli   '/home/mastodon/live/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.4.0
gyp info using node@8.13.0 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack TypeError: Cannot read property 'length' of undefined
gyp ERR! stack     at parse (/home/mastodon/live/node_modules/semver/semver.js:239:15)
gyp ERR! stack     at Function.valid (/home/mastodon/live/node_modules/semver/semver.js:255:11)
gyp ERR! stack     at processRelease (/home/mastodon/live/node_modules/node-gyp/lib/process-release.js:16:25)
gyp ERR! stack     at configure (/home/mastodon/live/node_modules/node-gyp/lib/configure.js:35:17)
gyp ERR! stack     at Object.self.commands.(anonymous function) [as configure] (/home/mastodon/live/node_modules/node-gyp/lib/node-gyp.js:66:37)
gyp ERR! stack     at run (/home/mastodon/live/node_modules/node-gyp/bin/node-gyp.js:72:30)
gyp ERR! stack     at _combinedTickCallback (internal/process/next_tick.js:132:7)
gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:181:9)
gyp ERR! System Linux 4.15.0-39-generic
gyp ERR! command "/usr/bin/node" "/home/mastodon/live/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/mastodon/live/node_modules/node-sass
gyp ERR! node -v v8.13.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
Build failed with error code: 7```

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bugs also occur on vanilla Mastodon

**Comment by ThibG** [comment]
I'm afraid I can't reproduce this and I don't know how to debug this :/
Maybe try with node 10 if you can?

**Comment by magicalraccoon** [comment]
I poked at things a bit more before I fell asleep last night. Reinstalled node-sass, ran `npm install`, `rbenv install`, `gem install bundle` and I guess it worked.
